// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type AuthFinishRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Result of the auth flow.
	AuthFinishResponse *components.AuthFinishResponse
}

func (a *AuthFinishRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthFinishRequestResponse) GetAuthFinishResponse() *components.AuthFinishResponse {
	if a == nil {
		return nil
	}
	return a.AuthFinishResponse
}
