// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type AuthStartRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Result of the operation.
	AuthStartResponse *components.AuthStartResponse
}

func (a *AuthStartRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AuthStartRequestResponse) GetAuthStartResponse() *components.AuthStartResponse {
	if a == nil {
		return nil
	}
	return a.AuthStartResponse
}
