// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3ActivateIdentityRequest struct {
	// A Prove-generated unique ID for a specific identity.
	IdentityID                string                                `pathParam:"style=simple,explode=false,name=identityId"`
	V3ActivateIdentityRequest *components.V3ActivateIdentityRequest `request:"mediaType=application/json"`
}

func (o *V3ActivateIdentityRequest) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

func (o *V3ActivateIdentityRequest) GetV3ActivateIdentityRequest() *components.V3ActivateIdentityRequest {
	if o == nil {
		return nil
	}
	return o.V3ActivateIdentityRequest
}

type V3ActivateIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3ActivateIdentityResponse
	V3ActivateIdentityResponse *components.V3ActivateIdentityResponse
}

func (o *V3ActivateIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3ActivateIdentityResponse) GetV3ActivateIdentityResponse() *components.V3ActivateIdentityResponse {
	if o == nil {
		return nil
	}
	return o.V3ActivateIdentityResponse
}
