// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3BatchEnrollIdentitiesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3BatchEnrollIdentitiesResponse
	V3BatchEnrollIdentitiesResponse *components.V3BatchEnrollIdentitiesResponse
}

func (v *V3BatchEnrollIdentitiesResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3BatchEnrollIdentitiesResponse) GetV3BatchEnrollIdentitiesResponse() *components.V3BatchEnrollIdentitiesResponse {
	if v == nil {
		return nil
	}
	return v.V3BatchEnrollIdentitiesResponse
}
