// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3ChallengeRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3ChallengeResponse *components.V3ChallengeResponse
}

func (v *V3ChallengeRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3ChallengeRequestResponse) GetV3ChallengeResponse() *components.V3ChallengeResponse {
	if v == nil {
		return nil
	}
	return v.V3ChallengeResponse
}
