// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3CompleteRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3CompleteResponse *components.V3CompleteResponse
}

func (v *V3CompleteRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3CompleteRequestResponse) GetV3CompleteResponse() *components.V3CompleteResponse {
	if v == nil {
		return nil
	}
	return v.V3CompleteResponse
}
