// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3CrossDomainIdentityRequest struct {
	// A Prove-generated unique ID for a specific identity.
	IdentityID                   string                                   `pathParam:"style=simple,explode=false,name=identityId"`
	V3CrossDomainIdentityRequest *components.V3CrossDomainIdentityRequest `request:"mediaType=application/json"`
}

func (v *V3CrossDomainIdentityRequest) GetIdentityID() string {
	if v == nil {
		return ""
	}
	return v.IdentityID
}

func (v *V3CrossDomainIdentityRequest) GetV3CrossDomainIdentityRequest() *components.V3CrossDomainIdentityRequest {
	if v == nil {
		return nil
	}
	return v.V3CrossDomainIdentityRequest
}

type V3CrossDomainIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3CrossDomainIdentityResponse
	V3CrossDomainIdentityResponse *components.V3CrossDomainIdentityResponse
}

func (v *V3CrossDomainIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3CrossDomainIdentityResponse) GetV3CrossDomainIdentityResponse() *components.V3CrossDomainIdentityResponse {
	if v == nil {
		return nil
	}
	return v.V3CrossDomainIdentityResponse
}
