// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3CrossDomainIdentityRequest struct {
	// A Prove-generated unique ID for a specific identity.
	IdentityID                   string                                   `pathParam:"style=simple,explode=false,name=identityId"`
	V3CrossDomainIdentityRequest *components.V3CrossDomainIdentityRequest `request:"mediaType=application/json"`
}

func (o *V3CrossDomainIdentityRequest) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

func (o *V3CrossDomainIdentityRequest) GetV3CrossDomainIdentityRequest() *components.V3CrossDomainIdentityRequest {
	if o == nil {
		return nil
	}
	return o.V3CrossDomainIdentityRequest
}

type V3CrossDomainIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3CrossDomainIdentityResponse
	V3CrossDomainIdentityResponse *components.V3CrossDomainIdentityResponse
}

func (o *V3CrossDomainIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3CrossDomainIdentityResponse) GetV3CrossDomainIdentityResponse() *components.V3CrossDomainIdentityResponse {
	if o == nil {
		return nil
	}
	return o.V3CrossDomainIdentityResponse
}
