// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DeactivateIdentityRequest struct {
	// A Prove-generated unique ID for a specific identity.
	ProveID                     string                                  `pathParam:"style=simple,explode=false,name=proveId"`
	V3IdentityDeactivateRequest *components.V3IdentityDeactivateRequest `request:"mediaType=application/json"`
}

func (v *V3DeactivateIdentityRequest) GetProveID() string {
	if v == nil {
		return ""
	}
	return v.ProveID
}

func (v *V3DeactivateIdentityRequest) GetV3IdentityDeactivateRequest() *components.V3IdentityDeactivateRequest {
	if v == nil {
		return nil
	}
	return v.V3IdentityDeactivateRequest
}

// #region class-body-v3deactivateidentityrequest
// #endregion class-body-v3deactivateidentityrequest

type V3DeactivateIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3DeactivateIdentityResponse
	V3DeactivateIdentityResponse *components.V3DeactivateIdentityResponse
}

func (v *V3DeactivateIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3DeactivateIdentityResponse) GetV3DeactivateIdentityResponse() *components.V3DeactivateIdentityResponse {
	if v == nil {
		return nil
	}
	return v.V3DeactivateIdentityResponse
}

// #region class-body-v3deactivateidentityresponse
// #endregion class-body-v3deactivateidentityresponse
