// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DiscoverRequestRequest struct {
	// A unique Prove-generated identifier for the enrolled identity (UUID).
	ProveID string `queryParam:"style=form,explode=true,name=proveId"`
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `queryParam:"style=form,explode=true,name=clientRequestId"`
}

func (v *V3DiscoverRequestRequest) GetProveID() string {
	if v == nil {
		return ""
	}
	return v.ProveID
}

func (v *V3DiscoverRequestRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

// #region class-body-v3discoverrequestrequest
// #endregion class-body-v3discoverrequestrequest

type V3DiscoverRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request.
	V3DiscoverResponse *components.V3DiscoverResponse
	Headers            map[string][]string
}

func (v *V3DiscoverRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3DiscoverRequestResponse) GetV3DiscoverResponse() *components.V3DiscoverResponse {
	if v == nil {
		return nil
	}
	return v.V3DiscoverResponse
}

func (v *V3DiscoverRequestResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}

// #region class-body-v3discoverrequestresponse
// #endregion class-body-v3discoverrequestresponse
