// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DomainLinkRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3DomainLinkResponse
	V3DomainLinkResponse *components.V3DomainLinkResponse
}

func (v *V3DomainLinkRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3DomainLinkRequestResponse) GetV3DomainLinkResponse() *components.V3DomainLinkResponse {
	if v == nil {
		return nil
	}
	return v.V3DomainLinkResponse
}
