// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DomainLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3DomainLinkResponse
	V3DomainLinkResponse *components.V3DomainLinkResponse
}

func (o *V3DomainLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3DomainLinkResponse) GetV3DomainLinkResponse() *components.V3DomainLinkResponse {
	if o == nil {
		return nil
	}
	return o.V3DomainLinkResponse
}
