// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DomainUnlinkRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3DomainUnlinkResponse
	V3DomainUnlinkResponse *components.V3DomainUnlinkResponse
}

func (o *V3DomainUnlinkRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3DomainUnlinkRequestResponse) GetV3DomainUnlinkResponse() *components.V3DomainUnlinkResponse {
	if o == nil {
		return nil
	}
	return o.V3DomainUnlinkResponse
}
