// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DomainLinkedRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3DomainLinkedResponse *components.V3DomainLinkedResponse
	Headers                map[string][]string
}

func (v *V3DomainLinkedRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3DomainLinkedRequestResponse) GetV3DomainLinkedResponse() *components.V3DomainLinkedResponse {
	if v == nil {
		return nil
	}
	return v.V3DomainLinkedResponse
}

func (v *V3DomainLinkedRequestResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
