// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3DomainLinkedResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3DomainLinkedResponse *components.V3DomainLinkedResponse
	Headers                map[string][]string
}

func (o *V3DomainLinkedResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3DomainLinkedResponse) GetV3DomainLinkedResponse() *components.V3DomainLinkedResponse {
	if o == nil {
		return nil
	}
	return o.V3DomainLinkedResponse
}

func (o *V3DomainLinkedResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
