// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3EnrollIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3EnrollIdentityResponse
	V3EnrollIdentityResponse *components.V3EnrollIdentityResponse
}

func (v *V3EnrollIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3EnrollIdentityResponse) GetV3EnrollIdentityResponse() *components.V3EnrollIdentityResponse {
	if v == nil {
		return nil
	}
	return v.V3EnrollIdentityResponse
}
