// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3GetIdentitiesByPhoneNumberRequest struct {
	// The phone number to find identities for. US phone numbers can be passed in with or without a leading +1. Acceptable characters are: alphanumeric with symbols '+'.
	MobileNumber string `pathParam:"style=simple,explode=false,name=mobileNumber"`
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `queryParam:"style=form,explode=true,name=clientRequestId"`
}

func (o *V3GetIdentitiesByPhoneNumberRequest) GetMobileNumber() string {
	if o == nil {
		return ""
	}
	return o.MobileNumber
}

func (o *V3GetIdentitiesByPhoneNumberRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

type V3GetIdentitiesByPhoneNumberResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3GetIdentitiesByPhoneNumberResponse
	V3GetIdentitiesByPhoneNumberResponse *components.V3GetIdentitiesByPhoneNumberResponse
}

func (o *V3GetIdentitiesByPhoneNumberResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3GetIdentitiesByPhoneNumberResponse) GetV3GetIdentitiesByPhoneNumberResponse() *components.V3GetIdentitiesByPhoneNumberResponse {
	if o == nil {
		return nil
	}
	return o.V3GetIdentitiesByPhoneNumberResponse
}
