// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3GetIdentityRequest struct {
	// A unique Prove-generated identifier for the enrolled identity.
	IdentityID string `pathParam:"style=simple,explode=false,name=identityId"`
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `queryParam:"style=form,explode=true,name=clientRequestId"`
}

func (v *V3GetIdentityRequest) GetIdentityID() string {
	if v == nil {
		return ""
	}
	return v.IdentityID
}

func (v *V3GetIdentityRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

type V3GetIdentityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// V3GetIdentityResponse
	V3GetIdentityResponse *components.V3GetIdentityResponse
}

func (v *V3GetIdentityResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3GetIdentityResponse) GetV3GetIdentityResponse() *components.V3GetIdentityResponse {
	if v == nil {
		return nil
	}
	return v.V3GetIdentityResponse
}
