// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3MFARequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3MFAResponse *components.V3MFAResponse
}

func (o *V3MFARequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3MFARequestResponse) GetV3MFAResponse() *components.V3MFAResponse {
	if o == nil {
		return nil
	}
	return o.V3MFAResponse
}
