// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3MFABindRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request
	V3MFABindResponse *components.V3MFABindResponse
	Headers           map[string][]string
}

func (o *V3MFABindRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3MFABindRequestResponse) GetV3MFABindResponse() *components.V3MFABindResponse {
	if o == nil {
		return nil
	}
	return o.V3MFABindResponse
}

func (o *V3MFABindRequestResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
