// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3MFAStatusRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request
	V3MFAStatusResponse *components.V3MFAStatusResponse
	Headers             map[string][]string
}

func (o *V3MFAStatusRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3MFAStatusRequestResponse) GetV3MFAStatusResponse() *components.V3MFAStatusResponse {
	if o == nil {
		return nil
	}
	return o.V3MFAStatusResponse
}

func (o *V3MFAStatusRequestResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
