// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3UnifyStatusRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request
	V3UnifyStatusResponse *components.V3UnifyStatusResponse
	Headers               map[string][]string
}

func (o *V3UnifyStatusRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V3UnifyStatusRequestResponse) GetV3UnifyStatusResponse() *components.V3UnifyStatusResponse {
	if o == nil {
		return nil
	}
	return o.V3UnifyStatusResponse
}

func (o *V3UnifyStatusRequestResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}
