// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3UnifyBindRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request.
	V3UnifyBindResponse *components.V3UnifyBindResponse
	Headers             map[string][]string
}

func (v *V3UnifyBindRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3UnifyBindRequestResponse) GetV3UnifyBindResponse() *components.V3UnifyBindResponse {
	if v == nil {
		return nil
	}
	return v.V3UnifyBindResponse
}

func (v *V3UnifyBindRequestResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
