// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3UnifyStatusRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request.
	V3UnifyStatusResponse *components.V3UnifyStatusResponse
	Headers               map[string][]string
}

func (v *V3UnifyStatusRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3UnifyStatusRequestResponse) GetV3UnifyStatusResponse() *components.V3UnifyStatusResponse {
	if v == nil {
		return nil
	}
	return v.V3UnifyStatusResponse
}

func (v *V3UnifyStatusRequestResponse) GetHeaders() map[string][]string {
	if v == nil {
		return map[string][]string{}
	}
	return v.Headers
}
