// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3UnifyRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful Request.
	V3UnifyResponse *components.V3UnifyResponse
}

func (v *V3UnifyRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3UnifyRequestResponse) GetV3UnifyResponse() *components.V3UnifyResponse {
	if v == nil {
		return nil
	}
	return v.V3UnifyResponse
}
