// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/prove-identity/prove-sdk-server-go/models/components"
)

type V3VerifyBatchRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful request.
	V3VerifyBatchResponse *components.V3VerifyBatchResponse
}

func (v *V3VerifyBatchRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *V3VerifyBatchRequestResponse) GetV3VerifyBatchResponse() *components.V3VerifyBatchResponse {
	if v == nil {
		return nil
	}
	return v.V3VerifyBatchResponse
}
