// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Error401 struct {
	// An internal error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// An error message describing the problem with the request.
	Message string `json:"message"`
}

var _ error = &Error401{}

func (e *Error401) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
