// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Error404 struct {
	// The input ClientRequestID, echoed when provided on the request.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// An error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// The correlation ID for the flow, echoed when available.
	CorrelationID *string `json:"correlationId,omitempty"`
	// The error message describing the problem with the request.
	Message string `json:"message"`
}

var _ error = &Error404{}

func (e *Error404) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
