// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// Error400 is a custom error for HTTP 400. This is used to support distinguishing
// between HTTP 400 and 500 in Speakeasy SDKs.
type Error400 struct {
	// Code is an internal error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// Message is an error message describing the problem with the request.
	Message string `json:"message"`
}

var _ error = &Error400{}

func (e *Error400) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
