// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Error403 struct {
	// An error code that identifies the specific authorization issue.
	Code *int64 `json:"code,omitempty"`
	// The error message describing why access is forbidden.
	Message string `json:"message"`
}

var _ error = &Error403{}

func (e *Error403) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
