// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AdditionalIdentity struct {
	// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
	AssuranceLevel string `json:"assuranceLevel"`
	// The first name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// Codes explaining the verification outcome
	Reasons []string `json:"reasons"`
}

func (a *AdditionalIdentity) GetAssuranceLevel() string {
	if a == nil {
		return ""
	}
	return a.AssuranceLevel
}

func (a *AdditionalIdentity) GetFirstName() *string {
	if a == nil {
		return nil
	}
	return a.FirstName
}

func (a *AdditionalIdentity) GetLastName() *string {
	if a == nil {
		return nil
	}
	return a.LastName
}

func (a *AdditionalIdentity) GetReasons() []string {
	if a == nil {
		return []string{}
	}
	return a.Reasons
}
