// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Address struct {
	Address         *string `json:"address,omitempty"`
	City            *string `json:"city,omitempty"`
	ExtendedAddress *string `json:"extendedAddress,omitempty"`
	Region          *string `json:"region,omitempty"`
	ZipCode         *string `json:"zipCode,omitempty"`
}

func (a *Address) GetAddress() *string {
	if a == nil {
		return nil
	}
	return a.Address
}

func (a *Address) GetCity() *string {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *Address) GetExtendedAddress() *string {
	if a == nil {
		return nil
	}
	return a.ExtendedAddress
}

func (a *Address) GetRegion() *string {
	if a == nil {
		return nil
	}
	return a.Region
}

func (a *Address) GetZipCode() *string {
	if a == nil {
		return nil
	}
	return a.ZipCode
}
