// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AmlTypeListResponseInternal struct {
	AmlType  *string                        `json:"amlType,omitempty"`
	Fields   []KYCFieldTypeResponseInternal `json:"fields,omitempty"`
	ListHits *int64                         `json:"listHits,omitempty"`
}

func (a *AmlTypeListResponseInternal) GetAmlType() *string {
	if a == nil {
		return nil
	}
	return a.AmlType
}

func (a *AmlTypeListResponseInternal) GetFields() []KYCFieldTypeResponseInternal {
	if a == nil {
		return nil
	}
	return a.Fields
}

func (a *AmlTypeListResponseInternal) GetListHits() *int64 {
	if a == nil {
		return nil
	}
	return a.ListHits
}
