// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestDeliveryPushNotification struct {
	// Body is the body of the push message.
	Body string `json:"body"`
	// ConfirmButton is the text of the push message confirm button.
	ConfirmBtn *string `json:"confirmBtn,omitempty"`
	// DenyButton is the text of the push message deny button.
	DenyBtn *string `json:"denyBtn,omitempty"`
	// OriginatingDevice is the type of device where where the push flow was initiated.
	OriginatingDevice *string `json:"originatingDevice,omitempty"`
	// OriginatingIp is the IP address of the web client where the push flow was initiated.
	OriginatingIP *string `json:"originatingIp,omitempty"`
	// Title is the title of the push message.
	Title string `json:"title"`
}

func (a *AuthStartRequestDeliveryPushNotification) GetBody() string {
	if a == nil {
		return ""
	}
	return a.Body
}

func (a *AuthStartRequestDeliveryPushNotification) GetConfirmBtn() *string {
	if a == nil {
		return nil
	}
	return a.ConfirmBtn
}

func (a *AuthStartRequestDeliveryPushNotification) GetDenyBtn() *string {
	if a == nil {
		return nil
	}
	return a.DenyBtn
}

func (a *AuthStartRequestDeliveryPushNotification) GetOriginatingDevice() *string {
	if a == nil {
		return nil
	}
	return a.OriginatingDevice
}

func (a *AuthStartRequestDeliveryPushNotification) GetOriginatingIP() *string {
	if a == nil {
		return nil
	}
	return a.OriginatingIP
}

func (a *AuthStartRequestDeliveryPushNotification) GetTitle() string {
	if a == nil {
		return ""
	}
	return a.Title
}
