// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponse struct {
	// AppNamespace describes the Prove Auth environment.
	AppNamespace string `json:"appNamespace"`
	// AuthID is the unique ID of the auth flow.
	AuthID   string                      `json:"authId"`
	Delivery *AuthFinishResponseDelivery `json:"delivery,omitempty"`
	Subjects AuthFinishResponseSubjects  `json:"subjects"`
}

func (a *AuthFinishResponse) GetAppNamespace() string {
	if a == nil {
		return ""
	}
	return a.AppNamespace
}

func (a *AuthFinishResponse) GetAuthID() string {
	if a == nil {
		return ""
	}
	return a.AuthID
}

func (a *AuthFinishResponse) GetDelivery() *AuthFinishResponseDelivery {
	if a == nil {
		return nil
	}
	return a.Delivery
}

func (a *AuthFinishResponse) GetSubjects() AuthFinishResponseSubjects {
	if a == nil {
		return AuthFinishResponseSubjects{}
	}
	return a.Subjects
}
