// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueResponseSubjectMobileResult struct {
	Error *AuthContinueResponseError `json:"error,omitempty"`
	// Success will be true if the bind was successful.
	Success bool `json:"success"`
}

func (a *AuthContinueResponseSubjectMobileResult) GetError() *AuthContinueResponseError {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AuthContinueResponseSubjectMobileResult) GetSuccess() bool {
	if a == nil {
		return false
	}
	return a.Success
}
