// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueResponse struct {
	Subjects AuthContinueResponseSubjectsResults `json:"subjects"`
}

func (a *AuthContinueResponse) GetSubjects() AuthContinueResponseSubjectsResults {
	if a == nil {
		return AuthContinueResponseSubjectsResults{}
	}
	return a.Subjects
}
