// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponsePushDelivery struct {
	Extras   *AuthFinishResponsePushDeliveryExtras `json:"extras,omitempty"`
	Response *string                               `json:"response,omitempty"`
}

func (a *AuthFinishResponsePushDelivery) GetExtras() *AuthFinishResponsePushDeliveryExtras {
	if a == nil {
		return nil
	}
	return a.Extras
}

func (a *AuthFinishResponsePushDelivery) GetResponse() *string {
	if a == nil {
		return nil
	}
	return a.Response
}
