// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectUserClaim struct {
	// Provided if true, registers the user ID with a device, otherwise it valids the user ID.
	Provided *bool `json:"provided,omitempty"`
	// UserID is a user identifier generated on the customer side to be associated with a device.
	// Acceptable characters are: alphanumeric with symbols '-._+=/:'.
	UserID string `json:"userId"`
}

func (a *AuthStartRequestSubjectUserClaim) GetProvided() *bool {
	if a == nil {
		return nil
	}
	return a.Provided
}

func (a *AuthStartRequestSubjectUserClaim) GetUserID() string {
	if a == nil {
		return ""
	}
	return a.UserID
}
