// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestDeliveryPush struct {
	Notification AuthStartRequestDeliveryPushNotification `json:"notification"`
}

func (a *AuthStartRequestDeliveryPush) GetNotification() AuthStartRequestDeliveryPushNotification {
	if a == nil {
		return AuthStartRequestDeliveryPushNotification{}
	}
	return a.Notification
}
