// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjects struct {
	Card   *AuthFinishResponseSubjectCardsResult  `json:"card,omitempty"`
	Device *AuthFinishResponseSubjectDeviceResult `json:"device,omitempty"`
	Mobile *AuthFinishResponseSubjectMobileResult `json:"mobile,omitempty"`
	User   *AuthFinishResponseSubjectUserResult   `json:"user,omitempty"`
}

func (a *AuthFinishResponseSubjects) GetCard() *AuthFinishResponseSubjectCardsResult {
	if a == nil {
		return nil
	}
	return a.Card
}

func (a *AuthFinishResponseSubjects) GetDevice() *AuthFinishResponseSubjectDeviceResult {
	if a == nil {
		return nil
	}
	return a.Device
}

func (a *AuthFinishResponseSubjects) GetMobile() *AuthFinishResponseSubjectMobileResult {
	if a == nil {
		return nil
	}
	return a.Mobile
}

func (a *AuthFinishResponseSubjects) GetUser() *AuthFinishResponseSubjectUserResult {
	if a == nil {
		return nil
	}
	return a.User
}
