// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobileAuthenticatorInstant struct {
	Consent  *AuthStartRequestInstantAuthConsent `json:"consent,omitempty"`
	TestMode *string                             `json:"testMode,omitempty"`
}

func (a *AuthStartRequestSubjectMobileAuthenticatorInstant) GetConsent() *AuthStartRequestInstantAuthConsent {
	if a == nil {
		return nil
	}
	return a.Consent
}

func (a *AuthStartRequestSubjectMobileAuthenticatorInstant) GetTestMode() *string {
	if a == nil {
		return nil
	}
	return a.TestMode
}
