// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseError struct {
	// Code is an internal error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// Message is an error message describing the problem with the request.
	Message string `json:"message"`
}

func (a *AuthFinishResponseError) GetCode() *int64 {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *AuthFinishResponseError) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}
