// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueRequestSubjects struct {
	Mobile *AuthContinueRequestSubjectMobile `json:"mobile,omitempty"`
}

func (a *AuthContinueRequestSubjects) GetMobile() *AuthContinueRequestSubjectMobile {
	if a == nil {
		return nil
	}
	return a.Mobile
}
