// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectUserResult struct {
	Error   *AuthFinishResponseError                    `json:"error,omitempty"`
	Success *AuthFinishResponseSubjectUserResultSuccess `json:"success,omitempty"`
}

func (a *AuthFinishResponseSubjectUserResult) GetError() *AuthFinishResponseError {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AuthFinishResponseSubjectUserResult) GetSuccess() *AuthFinishResponseSubjectUserResultSuccess {
	if a == nil {
		return nil
	}
	return a.Success
}
