// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueResponseSubjectCardResult struct {
	Error   *AuthContinueResponseError `json:"error,omitempty"`
	Success *bool                      `json:"success,omitempty"`
}

func (a *AuthContinueResponseSubjectCardResult) GetError() *AuthContinueResponseError {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AuthContinueResponseSubjectCardResult) GetSuccess() *bool {
	if a == nil {
		return nil
	}
	return a.Success
}
