// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueResponseSubjectsResults struct {
	Card   *AuthContinueResponseSubjectCardResult   `json:"card,omitempty"`
	Mobile *AuthContinueResponseSubjectMobileResult `json:"mobile,omitempty"`
}

func (a *AuthContinueResponseSubjectsResults) GetCard() *AuthContinueResponseSubjectCardResult {
	if a == nil {
		return nil
	}
	return a.Card
}

func (a *AuthContinueResponseSubjectsResults) GetMobile() *AuthContinueResponseSubjectMobileResult {
	if a == nil {
		return nil
	}
	return a.Mobile
}
