// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectMobileResultSuccessClaim struct {
	// MobileNumber bound to the device. Mobile number may be prefixed with a plus sign, but does not need to be for
	// US. A plus sign is required for international.
	MobileNumber string `json:"mobileNumber"`
}

func (a *AuthFinishResponseSubjectMobileResultSuccessClaim) GetMobileNumber() string {
	if a == nil {
		return ""
	}
	return a.MobileNumber
}
