// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestDeliveryScan struct {
	Notification AuthStartRequestDeliveryScanNotification `json:"notification"`
}

func (a *AuthStartRequestDeliveryScan) GetNotification() AuthStartRequestDeliveryScanNotification {
	if a == nil {
		return AuthStartRequestDeliveryScanNotification{}
	}
	return a.Notification
}
