// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Docv struct {
}

type Ppb struct {
}

type Present struct {
}

type AuthStartRequestSubjectUserAuthenticators struct {
	Docv    *Docv                                            `json:"docv,omitempty"`
	Passive *AuthStartRequestSubjectUserAuthenticatorPassive `json:"passive,omitempty"`
	Ppb     *Ppb                                             `json:"ppb,omitempty"`
	Present *Present                                         `json:"present,omitempty"`
}

func (a *AuthStartRequestSubjectUserAuthenticators) GetDocv() *Docv {
	if a == nil {
		return nil
	}
	return a.Docv
}

func (a *AuthStartRequestSubjectUserAuthenticators) GetPassive() *AuthStartRequestSubjectUserAuthenticatorPassive {
	if a == nil {
		return nil
	}
	return a.Passive
}

func (a *AuthStartRequestSubjectUserAuthenticators) GetPpb() *Ppb {
	if a == nil {
		return nil
	}
	return a.Ppb
}

func (a *AuthStartRequestSubjectUserAuthenticators) GetPresent() *Present {
	if a == nil {
		return nil
	}
	return a.Present
}
