// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseScanDeliveryExtras struct {
	OriginatingIPGeolocation *string `json:"originatingIpGeolocation,omitempty"`
}

func (a *AuthFinishResponseScanDeliveryExtras) GetOriginatingIPGeolocation() *string {
	if a == nil {
		return nil
	}
	return a.OriginatingIPGeolocation
}
