// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseCardError struct {
	// Code is an internal error code that describes the problem category of the request.
	Code *int64 `json:"code,omitempty"`
	// Message is an error message describing the problem with the request.
	Message string `json:"message"`
	// PUID is the unique ID associated with an AirKey card that was extracted from the AirKey message.
	Puid *string `json:"puid,omitempty"`
}

func (a *AuthFinishResponseCardError) GetCode() *int64 {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *AuthFinishResponseCardError) GetMessage() string {
	if a == nil {
		return ""
	}
	return a.Message
}

func (a *AuthFinishResponseCardError) GetPuid() *string {
	if a == nil {
		return nil
	}
	return a.Puid
}
