// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectUser struct {
	Authenticators *AuthStartRequestSubjectUserAuthenticators `json:"authenticators,omitempty"`
	Claim          *AuthStartRequestSubjectUserClaim          `json:"claim,omitempty"`
}

func (a *AuthStartRequestSubjectUser) GetAuthenticators() *AuthStartRequestSubjectUserAuthenticators {
	if a == nil {
		return nil
	}
	return a.Authenticators
}

func (a *AuthStartRequestSubjectUser) GetClaim() *AuthStartRequestSubjectUserClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}
