// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobileAuthenticatorUniversal struct {
	// FinalTargetURL is the customer server URL that will be called back by Prove's Web page
	// after UPK registration/verification ceremony is done.
	FinalTargetURL string  `json:"finalTargetUrl"`
	TestMode       *string `json:"testMode,omitempty"`
}

func (a *AuthStartRequestSubjectMobileAuthenticatorUniversal) GetFinalTargetURL() string {
	if a == nil {
		return ""
	}
	return a.FinalTargetURL
}

func (a *AuthStartRequestSubjectMobileAuthenticatorUniversal) GetTestMode() *string {
	if a == nil {
		return nil
	}
	return a.TestMode
}
