// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthenticationResults struct {
	// An indication of which mobile authentication method was used.
	Mobile *string `json:"mobile,omitempty"`
}

func (a *AuthenticationResults) GetMobile() *string {
	if a == nil {
		return nil
	}
	return a.Mobile
}
