// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectDeviceResultSuccessExtras struct {
	// DeviceCapabilities contains the available device capabilities (webauthn, face, fingerprint).
	DeviceCapabilities []string `json:"deviceCapabilities,omitempty"`
	// DeviceAuthType contains description of the type of client device used for auth: 'web' or 'mobile'.
	DeviceType *string `json:"deviceType,omitempty"`
	// KeyType indicates the type of the key used for the authentication. This parameter is only included with UPK transactions.
	KeyType    *string                       `json:"keyType,omitempty"`
	RawSignals *AuthFinishResponseRawSignals `json:"rawSignals,omitempty"`
	// SupportedUvLevel indicates the level of user verification supported on the device.
	SupportedUvLevel []int64                                `json:"supportedUvLevel,omitempty"`
	Trust            *SubjectDeviceResultSuccessExtrasTrust `json:"trust,omitempty"`
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetDeviceCapabilities() []string {
	if a == nil {
		return nil
	}
	return a.DeviceCapabilities
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetDeviceType() *string {
	if a == nil {
		return nil
	}
	return a.DeviceType
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetKeyType() *string {
	if a == nil {
		return nil
	}
	return a.KeyType
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetRawSignals() *AuthFinishResponseRawSignals {
	if a == nil {
		return nil
	}
	return a.RawSignals
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetSupportedUvLevel() []int64 {
	if a == nil {
		return nil
	}
	return a.SupportedUvLevel
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessExtras) GetTrust() *SubjectDeviceResultSuccessExtrasTrust {
	if a == nil {
		return nil
	}
	return a.Trust
}
