// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobileAuthenticators struct {
	Instant     *AuthStartRequestSubjectMobileAuthenticatorInstant     `json:"instant,omitempty"`
	Instantlink *AuthStartRequestSubjectMobileAuthenticatorInstantLink `json:"instantlink,omitempty"`
	Otp         *AuthStartRequestSubjectMobileAuthenticatorOTP         `json:"otp,omitempty"`
	Passive     *AuthStartRequestSubjectMobileAuthenticatorPassive     `json:"passive,omitempty"`
	Universal   *AuthStartRequestSubjectMobileAuthenticatorUniversal   `json:"universal,omitempty"`
}

func (a *AuthStartRequestSubjectMobileAuthenticators) GetInstant() *AuthStartRequestSubjectMobileAuthenticatorInstant {
	if a == nil {
		return nil
	}
	return a.Instant
}

func (a *AuthStartRequestSubjectMobileAuthenticators) GetInstantlink() *AuthStartRequestSubjectMobileAuthenticatorInstantLink {
	if a == nil {
		return nil
	}
	return a.Instantlink
}

func (a *AuthStartRequestSubjectMobileAuthenticators) GetOtp() *AuthStartRequestSubjectMobileAuthenticatorOTP {
	if a == nil {
		return nil
	}
	return a.Otp
}

func (a *AuthStartRequestSubjectMobileAuthenticators) GetPassive() *AuthStartRequestSubjectMobileAuthenticatorPassive {
	if a == nil {
		return nil
	}
	return a.Passive
}

func (a *AuthStartRequestSubjectMobileAuthenticators) GetUniversal() *AuthStartRequestSubjectMobileAuthenticatorUniversal {
	if a == nil {
		return nil
	}
	return a.Universal
}
