// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectMobileResult struct {
	Error   *AuthFinishResponseError                      `json:"error,omitempty"`
	Success *AuthFinishResponseSubjectMobileResultSuccess `json:"success,omitempty"`
}

func (a *AuthFinishResponseSubjectMobileResult) GetError() *AuthFinishResponseError {
	if a == nil {
		return nil
	}
	return a.Error
}

func (a *AuthFinishResponseSubjectMobileResult) GetSuccess() *AuthFinishResponseSubjectMobileResultSuccess {
	if a == nil {
		return nil
	}
	return a.Success
}
