// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartResponse struct {
	// AuthID is the unique ID of the auth flow. To complete the auth flow, the `authId` will also be used for the
	// AuthFinish request.
	AuthID string `json:"authId"`
	// AuthToken is a bearer token for use by the Prove Auth SDK.
	AuthToken string `json:"authToken"`
	// PushTokens is an array of Push Tokens for the customer to use to initiate push notifications via their own service.
	PushTokens []PushToken `json:"pushTokens,omitempty"`
	// UniversalRedirectURL is a Prove hosted endpoint for Universal Prove Key. URL query string also includes session authToken parameter.
	UniversalRedirectURL *string `json:"universalRedirectUrl,omitempty"`
}

func (a *AuthStartResponse) GetAuthID() string {
	if a == nil {
		return ""
	}
	return a.AuthID
}

func (a *AuthStartResponse) GetAuthToken() string {
	if a == nil {
		return ""
	}
	return a.AuthToken
}

func (a *AuthStartResponse) GetPushTokens() []PushToken {
	if a == nil {
		return nil
	}
	return a.PushTokens
}

func (a *AuthStartResponse) GetUniversalRedirectURL() *string {
	if a == nil {
		return nil
	}
	return a.UniversalRedirectURL
}
