// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectUserResultSuccessClaim struct {
	UserID *string `json:"userId,omitempty"`
}

func (a *AuthFinishResponseSubjectUserResultSuccessClaim) GetUserID() *string {
	if a == nil {
		return nil
	}
	return a.UserID
}
