// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectCardAuthenticatorAirKey struct {
	Claim    *AuthStartRequestSubjectCardAuthenticatorAirKeyClaim `json:"claim,omitempty"`
	TestMode *string                                              `json:"testMode,omitempty"`
}

func (a *AuthStartRequestSubjectCardAuthenticatorAirKey) GetClaim() *AuthStartRequestSubjectCardAuthenticatorAirKeyClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}

func (a *AuthStartRequestSubjectCardAuthenticatorAirKey) GetTestMode() *string {
	if a == nil {
		return nil
	}
	return a.TestMode
}
