// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectMobileResultSuccess struct {
	// AuthenticatorType specifies the type of authenticator used in the auth flow. Values: instant, passive, and
	// provided.
	AuthenticatorType string                                             `json:"authenticatorType"`
	Claim             *AuthFinishResponseSubjectMobileResultSuccessClaim `json:"claim,omitempty"`
	// CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
	CreatedAt *int64                                              `json:"createdAt,omitempty"`
	Extras    *AuthFinishResponseSubjectMobileResultSuccessExtras `json:"extras,omitempty"`
}

func (a *AuthFinishResponseSubjectMobileResultSuccess) GetAuthenticatorType() string {
	if a == nil {
		return ""
	}
	return a.AuthenticatorType
}

func (a *AuthFinishResponseSubjectMobileResultSuccess) GetClaim() *AuthFinishResponseSubjectMobileResultSuccessClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}

func (a *AuthFinishResponseSubjectMobileResultSuccess) GetCreatedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AuthFinishResponseSubjectMobileResultSuccess) GetExtras() *AuthFinishResponseSubjectMobileResultSuccessExtras {
	if a == nil {
		return nil
	}
	return a.Extras
}
