// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishRequest struct {
	// AuthID is the unique ID of the auth flow to retrieve the result.
	AuthID string `json:"authId"`
}

func (a *AuthFinishRequest) GetAuthID() string {
	if a == nil {
		return ""
	}
	return a.AuthID
}
