// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectDeviceResultSuccessClaim struct {
	// DeviceID is the unique ID of the device.
	DeviceID string `json:"deviceId"`
}

func (a *AuthFinishResponseSubjectDeviceResultSuccessClaim) GetDeviceID() string {
	if a == nil {
		return ""
	}
	return a.DeviceID
}
