// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectMobile struct {
	Authenticators *AuthStartRequestSubjectMobileAuthenticators `json:"authenticators,omitempty"`
	Claim          *AuthStartRequestSubjectMobileClaim          `json:"claim,omitempty"`
}

func (a *AuthStartRequestSubjectMobile) GetAuthenticators() *AuthStartRequestSubjectMobileAuthenticators {
	if a == nil {
		return nil
	}
	return a.Authenticators
}

func (a *AuthStartRequestSubjectMobile) GetClaim() *AuthStartRequestSubjectMobileClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}
