// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequest struct {
	// CallbackURL is an optional callback URL (webhook) where Prove Auth will delivery the user's Push Auth response at
	// the end of the auth flow. If there are any errors encountered during the auth flow, those will be delivered to
	// the callback URL as well. If not provided, the customer server must call the AuthFinish endpoint to retrieve the
	// auth results. The request will be sent as a POST and will contain the same response body as the AuthFinish
	// response.
	CallbackURL *string                   `json:"callbackUrl,omitempty"`
	Delivery    *AuthStartRequestDelivery `json:"delivery,omitempty"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID string                   `json:"requestId"`
	Subjects  AuthStartRequestSubjects `json:"subjects"`
}

func (a *AuthStartRequest) GetCallbackURL() *string {
	if a == nil {
		return nil
	}
	return a.CallbackURL
}

func (a *AuthStartRequest) GetDelivery() *AuthStartRequestDelivery {
	if a == nil {
		return nil
	}
	return a.Delivery
}

func (a *AuthStartRequest) GetRequestID() string {
	if a == nil {
		return ""
	}
	return a.RequestID
}

func (a *AuthStartRequest) GetSubjects() AuthStartRequestSubjects {
	if a == nil {
		return AuthStartRequestSubjects{}
	}
	return a.Subjects
}
