// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthStartRequestSubjectDevice struct {
	Authenticators *AuthStartRequestSubjectDeviceAuthenticators `json:"authenticators,omitempty"`
	Claim          *AuthStartRequestSubjectDeviceClaim          `json:"claim,omitempty"`
}

func (a *AuthStartRequestSubjectDevice) GetAuthenticators() *AuthStartRequestSubjectDeviceAuthenticators {
	if a == nil {
		return nil
	}
	return a.Authenticators
}

func (a *AuthStartRequestSubjectDevice) GetClaim() *AuthStartRequestSubjectDeviceClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}
