// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthContinueRequest struct {
	// AuthID is the unique ID of the auth flow to continue.
	AuthID string `json:"authId"`
	// RequestID is a UUID generated on the customer side to be associated with the unique request for tracking.
	// Acceptable characters are: alphanumeric with symbols '-._+=/'.
	RequestID string                      `json:"requestId"`
	Subjects  AuthContinueRequestSubjects `json:"subjects"`
}

func (a *AuthContinueRequest) GetAuthID() string {
	if a == nil {
		return ""
	}
	return a.AuthID
}

func (a *AuthContinueRequest) GetRequestID() string {
	if a == nil {
		return ""
	}
	return a.RequestID
}

func (a *AuthContinueRequest) GetSubjects() AuthContinueRequestSubjects {
	if a == nil {
		return AuthContinueRequestSubjects{}
	}
	return a.Subjects
}
