// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthFinishResponseSubjectUserResultSuccess struct {
	AuthenticatorType *string                                          `json:"authenticatorType,omitempty"`
	Claim             *AuthFinishResponseSubjectUserResultSuccessClaim `json:"claim,omitempty"`
	// CreatedAt field is in Unix time which is the number of seconds elapsed since January 1, 1970 UTC.
	CreatedAt *int64                        `json:"createdAt,omitempty"`
	Extras    *AuthFinishResponseUserExtras `json:"extras,omitempty"`
}

func (a *AuthFinishResponseSubjectUserResultSuccess) GetAuthenticatorType() *string {
	if a == nil {
		return nil
	}
	return a.AuthenticatorType
}

func (a *AuthFinishResponseSubjectUserResultSuccess) GetClaim() *AuthFinishResponseSubjectUserResultSuccessClaim {
	if a == nil {
		return nil
	}
	return a.Claim
}

func (a *AuthFinishResponseSubjectUserResultSuccess) GetCreatedAt() *int64 {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AuthFinishResponseSubjectUserResultSuccess) GetExtras() *AuthFinishResponseUserExtras {
	if a == nil {
		return nil
	}
	return a.Extras
}
