// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Business struct {
	BusinessAddress    *BusinessAddress    `json:"businessAddress,omitempty"`
	BusinessName       *string             `json:"businessName,omitempty"`
	RegistrationFiling *RegistrationFiling `json:"registrationFiling,omitempty"`
	RelatedPersons     []RelatedPerson     `json:"relatedPersons,omitempty"`
	TaxID              *string             `json:"taxId,omitempty"`
	TradeName          *string             `json:"tradeName,omitempty"`
}

func (b *Business) GetBusinessAddress() *BusinessAddress {
	if b == nil {
		return nil
	}
	return b.BusinessAddress
}

func (b *Business) GetBusinessName() *string {
	if b == nil {
		return nil
	}
	return b.BusinessName
}

func (b *Business) GetRegistrationFiling() *RegistrationFiling {
	if b == nil {
		return nil
	}
	return b.RegistrationFiling
}

func (b *Business) GetRelatedPersons() []RelatedPerson {
	if b == nil {
		return nil
	}
	return b.RelatedPersons
}

func (b *Business) GetTaxID() *string {
	if b == nil {
		return nil
	}
	return b.TaxID
}

func (b *Business) GetTradeName() *string {
	if b == nil {
		return nil
	}
	return b.TradeName
}
