// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DataSourceAddressResponseInternal struct {
	AddressScore *int64   `json:"addressScore,omitempty"`
	City         *bool    `json:"city,omitempty"`
	Distance     *float64 `json:"distance,omitempty"`
	PostalCode   *bool    `json:"postalCode,omitempty"`
	Region       *bool    `json:"region,omitempty"`
	Street       *bool    `json:"street,omitempty"`
	StreetNumber *int64   `json:"streetNumber,omitempty"`
}

func (d *DataSourceAddressResponseInternal) GetAddressScore() *int64 {
	if d == nil {
		return nil
	}
	return d.AddressScore
}

func (d *DataSourceAddressResponseInternal) GetCity() *bool {
	if d == nil {
		return nil
	}
	return d.City
}

func (d *DataSourceAddressResponseInternal) GetDistance() *float64 {
	if d == nil {
		return nil
	}
	return d.Distance
}

func (d *DataSourceAddressResponseInternal) GetPostalCode() *bool {
	if d == nil {
		return nil
	}
	return d.PostalCode
}

func (d *DataSourceAddressResponseInternal) GetRegion() *bool {
	if d == nil {
		return nil
	}
	return d.Region
}

func (d *DataSourceAddressResponseInternal) GetStreet() *bool {
	if d == nil {
		return nil
	}
	return d.Street
}

func (d *DataSourceAddressResponseInternal) GetStreetNumber() *int64 {
	if d == nil {
		return nil
	}
	return d.StreetNumber
}
