// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DataSourceEmailAddressResponseInternal struct {
	EmailAddress *bool `json:"emailAddress,omitempty"`
}

func (d *DataSourceEmailAddressResponseInternal) GetEmailAddress() *bool {
	if d == nil {
		return nil
	}
	return d.EmailAddress
}
