// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type FetchResult struct {
	// A unique Prove-generated identifier for the identity attribute. This is a UUID that can be used to reference the attribute in future requests.
	AttributeID string `json:"attributeId"`
	// The actual value of the identity attribute. For example, if the attributeType is "walletId", this would contain the actual wallet identifier from the issuer.
	AttributeValue string `json:"attributeValue"`
	// A human-readable name for the issuer of the attribute. This identifies the partner or service provider that issued the attribute (e.g., "Aeropay", "Google Pay", "Apple Pay").
	IssuerID string `json:"issuerId"`
}

func (f *FetchResult) GetAttributeID() string {
	if f == nil {
		return ""
	}
	return f.AttributeID
}

func (f *FetchResult) GetAttributeValue() string {
	if f == nil {
		return ""
	}
	return f.AttributeValue
}

func (f *FetchResult) GetIssuerID() string {
	if f == nil {
		return ""
	}
	return f.IssuerID
}
