// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IdentityAttribute struct {
	AttributeType  *string `json:"attributeType,omitempty"`
	AttributeValue *string `json:"attributeValue,omitempty"`
}

func (i *IdentityAttribute) GetAttributeType() *string {
	if i == nil {
		return nil
	}
	return i.AttributeType
}

func (i *IdentityAttribute) GetAttributeValue() *string {
	if i == nil {
		return nil
	}
	return i.AttributeValue
}
