// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Identity struct {
	Addresses []Address `json:"addresses,omitempty"`
	// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
	AssuranceLevel string `json:"assuranceLevel"`
	// (required IF verificationType=VerifiedUser)
	ClientHumanID *string `json:"clientHumanId,omitempty"`
	// TODO: comments and validation
	DateOfBirth *string  `json:"dateOfBirth,omitempty"`
	Emails      []string `json:"emails,omitempty"`
	// The first name of the individual. (required IF verificationType=VerifiedUser)
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the individual. (required IF verificationType=VerifiedUser)
	LastName   *string `json:"lastName,omitempty"`
	MaxAge     *int64  `json:"maxAge,omitempty"`
	MinAge     *int64  `json:"minAge,omitempty"`
	NationalID *string `json:"nationalId,omitempty"`
	// Codes explaining the verification outcome
	Reasons []string `json:"reasons"`
}

func (i *Identity) GetAddresses() []Address {
	if i == nil {
		return nil
	}
	return i.Addresses
}

func (i *Identity) GetAssuranceLevel() string {
	if i == nil {
		return ""
	}
	return i.AssuranceLevel
}

func (i *Identity) GetClientHumanID() *string {
	if i == nil {
		return nil
	}
	return i.ClientHumanID
}

func (i *Identity) GetDateOfBirth() *string {
	if i == nil {
		return nil
	}
	return i.DateOfBirth
}

func (i *Identity) GetEmails() []string {
	if i == nil {
		return nil
	}
	return i.Emails
}

func (i *Identity) GetFirstName() *string {
	if i == nil {
		return nil
	}
	return i.FirstName
}

func (i *Identity) GetLastName() *string {
	if i == nil {
		return nil
	}
	return i.LastName
}

func (i *Identity) GetMaxAge() *int64 {
	if i == nil {
		return nil
	}
	return i.MaxAge
}

func (i *Identity) GetMinAge() *int64 {
	if i == nil {
		return nil
	}
	return i.MinAge
}

func (i *Identity) GetNationalID() *string {
	if i == nil {
		return nil
	}
	return i.NationalID
}

func (i *Identity) GetReasons() []string {
	if i == nil {
		return []string{}
	}
	return i.Reasons
}
