// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type IdentityItem struct {
	// The name of the client associated with the identity.
	ClientName string `json:"clientName"`
	// The Prove-generated unique ID for the specific identity.
	IdentityID string `json:"identityId"`
	// The Prove Customer ID (PCID) associated with the identity.
	Pcid string `json:"pcid"`
}

func (o *IdentityItem) GetClientName() string {
	if o == nil {
		return ""
	}
	return o.ClientName
}

func (o *IdentityItem) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

func (o *IdentityItem) GetPcid() string {
	if o == nil {
		return ""
	}
	return o.Pcid
}
