// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Identity struct {
	// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
	AssuranceLevel string `json:"assuranceLevel"`
	// The first name of the identity.
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the identity.
	LastName *string `json:"lastName,omitempty"`
	// Codes explaining the verification outcome
	Reasons []string `json:"reasons"`
}

func (i *Identity) GetAssuranceLevel() string {
	if i == nil {
		return ""
	}
	return i.AssuranceLevel
}

func (i *Identity) GetFirstName() *string {
	if i == nil {
		return nil
	}
	return i.FirstName
}

func (i *Identity) GetLastName() *string {
	if i == nil {
		return nil
	}
	return i.LastName
}

func (i *Identity) GetReasons() []string {
	if i == nil {
		return []string{}
	}
	return i.Reasons
}
