// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KYCFieldTypeResponseInternal struct {
	Name   *string `json:"name,omitempty"`
	Source *string `json:"source,omitempty"`
	Value  *string `json:"value,omitempty"`
}

func (k *KYCFieldTypeResponseInternal) GetName() *string {
	if k == nil {
		return nil
	}
	return k.Name
}

func (k *KYCFieldTypeResponseInternal) GetSource() *string {
	if k == nil {
		return nil
	}
	return k.Source
}

func (k *KYCFieldTypeResponseInternal) GetValue() *string {
	if k == nil {
		return nil
	}
	return k.Value
}
