// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type KYCInternal struct {
	AmlTypeLists []AmlTypeListResponseInternal `json:"amlTypeLists,omitempty"`
	TotalHits    *int64                        `json:"totalHits,omitempty"`
}

func (k *KYCInternal) GetAmlTypeLists() []AmlTypeListResponseInternal {
	if k == nil {
		return nil
	}
	return k.AmlTypeLists
}

func (k *KYCInternal) GetTotalHits() *int64 {
	if k == nil {
		return nil
	}
	return k.TotalHits
}
