// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedFrom struct {
	AcceptedAt     *int64  `json:"acceptedAt,omitempty"`
	AcceptedString *string `json:"acceptedString,omitempty"`
	Name           *string `json:"name,omitempty"`
	Pcid           *string `json:"pcid,omitempty"`
}

func (l *LinkedFrom) GetAcceptedAt() *int64 {
	if l == nil {
		return nil
	}
	return l.AcceptedAt
}

func (l *LinkedFrom) GetAcceptedString() *string {
	if l == nil {
		return nil
	}
	return l.AcceptedString
}

func (l *LinkedFrom) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LinkedFrom) GetPcid() *string {
	if l == nil {
		return nil
	}
	return l.Pcid
}
