// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type LinkedFrom struct {
	AcceptedAt     *int64  `json:"acceptedAt,omitempty"`
	AcceptedString *string `json:"acceptedString,omitempty"`
	Name           *string `json:"name,omitempty"`
	Pcid           *string `json:"pcid,omitempty"`
}

func (o *LinkedFrom) GetAcceptedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.AcceptedAt
}

func (o *LinkedFrom) GetAcceptedString() *string {
	if o == nil {
		return nil
	}
	return o.AcceptedString
}

func (o *LinkedFrom) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *LinkedFrom) GetPcid() *string {
	if o == nil {
		return nil
	}
	return o.Pcid
}
