// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// LookupIdentityItem - An Identity associated with the given phone number.
type LookupIdentityItem struct {
	// If true, the identity is currently active.
	Active *bool `json:"active,omitempty"`
	// The carrier associated with this identity/mobile number.
	Carrier *string `json:"carrier,omitempty"`
	// A client-generated unique ID for a specific customer. This can be used by clients to link calls related to the same customer, across different requests or sessions.  The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// The country code associated with the customer/identity. This will be in the ISO 3166-1 A-2 format.
	CountryCode *string `json:"countryCode,omitempty"`
	// The time that this identity was created, in seconds since the Unix epoch.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// The time that this identity was created, in ISO 8601 format.
	CreationString *string `json:"creationString,omitempty"`
	// A string that is the unique identifier for the Prove Key on the device. Only applicable if you are leveraging Prove Unify.
	DeviceID *string `json:"deviceId,omitempty"`
	// A Prove-generated unique ID for a specific identity.
	IdentityID *string `json:"identityId,omitempty"`
	// The type of line associated with this identity/mobile number.
	LineType *string `json:"lineType,omitempty"`
	// The number of the mobile phone. Refer to the Prove Pre-Fill with Mobile Auth and Prove Identity with Mobile Auth documentation for situations where this field is not required. US phone numbers can be passed in with or without a leading +1. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber string `json:"phoneNumber"`
}

func (l *LookupIdentityItem) GetActive() *bool {
	if l == nil {
		return nil
	}
	return l.Active
}

func (l *LookupIdentityItem) GetCarrier() *string {
	if l == nil {
		return nil
	}
	return l.Carrier
}

func (l *LookupIdentityItem) GetClientCustomerID() *string {
	if l == nil {
		return nil
	}
	return l.ClientCustomerID
}

func (l *LookupIdentityItem) GetCountryCode() *string {
	if l == nil {
		return nil
	}
	return l.CountryCode
}

func (l *LookupIdentityItem) GetCreatedAt() *int64 {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *LookupIdentityItem) GetCreationString() *string {
	if l == nil {
		return nil
	}
	return l.CreationString
}

func (l *LookupIdentityItem) GetDeviceID() *string {
	if l == nil {
		return nil
	}
	return l.DeviceID
}

func (l *LookupIdentityItem) GetIdentityID() *string {
	if l == nil {
		return nil
	}
	return l.IdentityID
}

func (l *LookupIdentityItem) GetLineType() *string {
	if l == nil {
		return nil
	}
	return l.LineType
}

func (l *LookupIdentityItem) GetPhoneNumber() string {
	if l == nil {
		return ""
	}
	return l.PhoneNumber
}
