// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PostBatchResultItem - Represents a single identity item in the response.
type PostBatchResultItem struct {
	// An error message that is returned if the identity cannot be successfully enrolled.
	Error *string `json:"error,omitempty"`
	// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
	IdentityID *string `json:"identityId,omitempty"`
}

func (p *PostBatchResultItem) GetError() *string {
	if p == nil {
		return nil
	}
	return p.Error
}

func (p *PostBatchResultItem) GetIdentityID() *string {
	if p == nil {
		return nil
	}
	return p.IdentityID
}
