// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RegistrationFiling struct {
	Date               *string `json:"date,omitempty"`
	Region             *string `json:"region,omitempty"`
	RegistrationNumber *string `json:"registrationNumber,omitempty"`
	RegistrationType   *string `json:"registrationType,omitempty"`
}

func (r *RegistrationFiling) GetDate() *string {
	if r == nil {
		return nil
	}
	return r.Date
}

func (r *RegistrationFiling) GetRegion() *string {
	if r == nil {
		return nil
	}
	return r.Region
}

func (r *RegistrationFiling) GetRegistrationNumber() *string {
	if r == nil {
		return nil
	}
	return r.RegistrationNumber
}

func (r *RegistrationFiling) GetRegistrationType() *string {
	if r == nil {
		return nil
	}
	return r.RegistrationType
}
