// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RelatedPerson struct {
	FirstName  *string `json:"firstName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	MiddleName *string `json:"middleName,omitempty"`
	Title      *string `json:"title,omitempty"`
}

func (r *RelatedPerson) GetFirstName() *string {
	if r == nil {
		return nil
	}
	return r.FirstName
}

func (r *RelatedPerson) GetLastName() *string {
	if r == nil {
		return nil
	}
	return r.LastName
}

func (r *RelatedPerson) GetMiddleName() *string {
	if r == nil {
		return nil
	}
	return r.MiddleName
}

func (r *RelatedPerson) GetTitle() *string {
	if r == nil {
		return nil
	}
	return r.Title
}
