// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RelatedPerson struct {
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

func (r *RelatedPerson) GetFirstName() *string {
	if r == nil {
		return nil
	}
	return r.FirstName
}

func (r *RelatedPerson) GetLastName() *string {
	if r == nil {
		return nil
	}
	return r.LastName
}
