// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RequestsFrom struct {
	Name            *string `json:"name,omitempty"`
	Pcid            *string `json:"pcid,omitempty"`
	RequestedAt     *int64  `json:"requestedAt,omitempty"`
	RequestedString *string `json:"requestedString,omitempty"`
}

func (r *RequestsFrom) GetName() *string {
	if r == nil {
		return nil
	}
	return r.Name
}

func (r *RequestsFrom) GetPcid() *string {
	if r == nil {
		return nil
	}
	return r.Pcid
}

func (r *RequestsFrom) GetRequestedAt() *int64 {
	if r == nil {
		return nil
	}
	return r.RequestedAt
}

func (r *RequestsFrom) GetRequestedString() *string {
	if r == nil {
		return nil
	}
	return r.RequestedString
}
