// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type RequestsFrom struct {
	Name            *string `json:"name,omitempty"`
	Pcid            *string `json:"pcid,omitempty"`
	RequestedAt     *int64  `json:"requestedAt,omitempty"`
	RequestedString *string `json:"requestedString,omitempty"`
}

func (o *RequestsFrom) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *RequestsFrom) GetPcid() *string {
	if o == nil {
		return nil
	}
	return o.Pcid
}

func (o *RequestsFrom) GetRequestedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.RequestedAt
}

func (o *RequestsFrom) GetRequestedString() *string {
	if o == nil {
		return nil
	}
	return o.RequestedString
}
