// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/prove-identity/prove-sdk-server-go/internal/utils"
)

type Security struct {
	ClientID     *string `security:"scheme,type=oauth2,subtype=client_credentials,name=clientID"`
	ClientSecret *string `security:"scheme,type=oauth2,subtype=client_credentials,name=clientSecret"`
	TokenURL     *string `default:"/token"`
}

func (s Security) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Security) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Security) GetClientID() *string {
	if s == nil {
		return nil
	}
	return s.ClientID
}

func (s *Security) GetClientSecret() *string {
	if s == nil {
		return nil
	}
	return s.ClientSecret
}

func (s *Security) GetTokenURL() *string {
	if s == nil {
		return nil
	}
	return s.TokenURL
}
