// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserTrustScore struct {
	Fused     *float64   `json:"fused,omitempty"`
	Reasons   *int64     `json:"reasons,omitempty"`
	SubScores *SubScores `json:"subScores,omitempty"`
}

func (u *UserTrustScore) GetFused() *float64 {
	if u == nil {
		return nil
	}
	return u.Fused
}

func (u *UserTrustScore) GetReasons() *int64 {
	if u == nil {
		return nil
	}
	return u.Reasons
}

func (u *UserTrustScore) GetSubScores() *SubScores {
	if u == nil {
		return nil
	}
	return u.SubScores
}
