// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3ActivateIdentityResponse - Response body for the V3 Activate Identity API.
type V3ActivateIdentityResponse struct {
	// If true, the activate operation was successful.
	Success bool `json:"success"`
}

func (v *V3ActivateIdentityResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}
