// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3BatchEnrollIdentitiesRequest - Request body for the V3 Batch Enroll Identities API.
type V3BatchEnrollIdentitiesRequest struct {
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string        `json:"clientRequestId,omitempty"`
	Items           []IdentityItem `json:"items,omitempty"`
}

func (o *V3BatchEnrollIdentitiesRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

func (o *V3BatchEnrollIdentitiesRequest) GetItems() []IdentityItem {
	if o == nil {
		return nil
	}
	return o.Items
}
