// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3BatchEnrollIdentitiesResponse - Response body for the V3 Batch Enroll Identities API.
type V3BatchEnrollIdentitiesResponse struct {
	Results []PostBatchResultItem `json:"results,omitempty"`
}

func (o *V3BatchEnrollIdentitiesResponse) GetResults() []PostBatchResultItem {
	if o == nil {
		return nil
	}
	return o.Results
}
