// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3BatchGetIdentitiesResponse - Response body for the V3 Batch Get Identities API.
type V3BatchGetIdentitiesResponse struct {
	// A pagination token for callers that have more identities left to return. Pass this back in directly to the Get Batch API with the startKey query parameter to get the next page of results.
	LastKey *string `json:"lastKey,omitempty"`
	// The list of identity IDs associated with the client.
	Results []GetBatchIdentityItem `json:"results"`
}

func (v *V3BatchGetIdentitiesResponse) GetLastKey() *string {
	if v == nil {
		return nil
	}
	return v.LastKey
}

func (v *V3BatchGetIdentitiesResponse) GetResults() []GetBatchIdentityItem {
	if v == nil {
		return []GetBatchIdentityItem{}
	}
	return v.Results
}
