// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ChallengeRequest struct {
	// The unique ID that Prove generates for the flow. It is returned from the Start endpoint and cannot be reused outside of a single flow.
	CorrelationID string `json:"correlationId"`
	// The date of birth in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
	Dob *string `json:"dob,omitempty"`
	// The full or last 4 numbers of the social security number. Acceptable characters are: numeric.
	Ssn *string `json:"ssn,omitempty"`
}

func (v *V3ChallengeRequest) GetCorrelationID() string {
	if v == nil {
		return ""
	}
	return v.CorrelationID
}

func (v *V3ChallengeRequest) GetDob() *string {
	if v == nil {
		return nil
	}
	return v.Dob
}

func (v *V3ChallengeRequest) GetSsn() *string {
	if v == nil {
		return nil
	}
	return v.Ssn
}
