// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ChallengeIndividualRequest struct {
	// An array of addresses that belong to the individual.
	Addresses []V3ChallengeAddressEntryRequest `json:"addresses,omitempty"`
	// The date of birth of the individual.
	Dob *string `json:"dob,omitempty"`
	// An array of email addresses that belong to the individual.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// The first name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// The social security number of the individual.
	Ssn *string `json:"ssn,omitempty"`
}

func (v *V3ChallengeIndividualRequest) GetAddresses() []V3ChallengeAddressEntryRequest {
	if v == nil {
		return nil
	}
	return v.Addresses
}

func (v *V3ChallengeIndividualRequest) GetDob() *string {
	if v == nil {
		return nil
	}
	return v.Dob
}

func (v *V3ChallengeIndividualRequest) GetEmailAddresses() []string {
	if v == nil {
		return nil
	}
	return v.EmailAddresses
}

func (v *V3ChallengeIndividualRequest) GetFirstName() *string {
	if v == nil {
		return nil
	}
	return v.FirstName
}

func (v *V3ChallengeIndividualRequest) GetLastName() *string {
	if v == nil {
		return nil
	}
	return v.LastName
}

func (v *V3ChallengeIndividualRequest) GetSsn() *string {
	if v == nil {
		return nil
	}
	return v.Ssn
}
