// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3CompleteResponseEvaluation struct {
}

type V3CompleteResponse struct {
	// The evaluation result for the policy
	Evaluation map[string]V3CompleteResponseEvaluation `json:"evaluation,omitempty"`
	Idv        *IDVDataInternal                        `json:"idv,omitempty"`
	Kyc        *KYCInternal                            `json:"kyc,omitempty"`
	// The next set of allowed calls in the same flow.
	Next map[string]string `json:"next"`
	// True if the individual was verified successfully.
	Success bool `json:"success"`
}

func (v *V3CompleteResponse) GetEvaluation() map[string]V3CompleteResponseEvaluation {
	if v == nil {
		return nil
	}
	return v.Evaluation
}

func (v *V3CompleteResponse) GetIdv() *IDVDataInternal {
	if v == nil {
		return nil
	}
	return v.Idv
}

func (v *V3CompleteResponse) GetKyc() *KYCInternal {
	if v == nil {
		return nil
	}
	return v.Kyc
}

func (v *V3CompleteResponse) GetNext() map[string]string {
	if v == nil {
		return map[string]string{}
	}
	return v.Next
}

func (v *V3CompleteResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}
