// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3CompleteIndividualRequest struct {
	// Address of the individual. Note that though this is an array, only the first address in the array will be processed.
	Addresses []V3CompleteAddressEntryRequest `json:"addresses,omitempty"`
	// The date of birth of the individual in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
	Dob *string `json:"dob,omitempty"`
	// Email address of the individual. Note that though this is an array, only the first email address in the array will be processed.
	EmailAddresses []string `json:"emailAddresses,omitempty"`
	// The first name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// The last name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// The social security number of the individual.
	Ssn *string `json:"ssn,omitempty"`
}

func (v *V3CompleteIndividualRequest) GetAddresses() []V3CompleteAddressEntryRequest {
	if v == nil {
		return nil
	}
	return v.Addresses
}

func (v *V3CompleteIndividualRequest) GetDob() *string {
	if v == nil {
		return nil
	}
	return v.Dob
}

func (v *V3CompleteIndividualRequest) GetEmailAddresses() []string {
	if v == nil {
		return nil
	}
	return v.EmailAddresses
}

func (v *V3CompleteIndividualRequest) GetFirstName() *string {
	if v == nil {
		return nil
	}
	return v.FirstName
}

func (v *V3CompleteIndividualRequest) GetLastName() *string {
	if v == nil {
		return nil
	}
	return v.LastName
}

func (v *V3CompleteIndividualRequest) GetSsn() *string {
	if v == nil {
		return nil
	}
	return v.Ssn
}
