// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3CrossDomainIdentityResponse - Response body for the V3 Identity Cross Domain API.
type V3CrossDomainIdentityResponse struct {
	// The number of items in the Identities array.
	Count int64 `json:"count"`
	// The list of identities from other linked accounts.
	Identites []IdentityItem `json:"identites"`
}

func (v *V3CrossDomainIdentityResponse) GetCount() int64 {
	if v == nil {
		return 0
	}
	return v.Count
}

func (v *V3CrossDomainIdentityResponse) GetIdentites() []IdentityItem {
	if v == nil {
		return []IdentityItem{}
	}
	return v.Identites
}
