// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DeviceRevokeResponse struct {
	// Whether the device was successfully revoked.
	Success bool `json:"success"`
}

func (v *V3DeviceRevokeResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}
