// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DeviceRevokeRequest struct {
	// A client-generated unique ID for a specific session. This can be used to identify specific requests.
	// The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
	// Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID string `json:"clientRequestId"`
	// The unique identifier for the Prove Key on the device.
	DeviceID string `json:"deviceId"`
}

func (v *V3DeviceRevokeRequest) GetClientRequestID() string {
	if v == nil {
		return ""
	}
	return v.ClientRequestID
}

func (v *V3DeviceRevokeRequest) GetDeviceID() string {
	if v == nil {
		return ""
	}
	return v.DeviceID
}
