// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3DeactivateIdentityResponse - Response body for the V3 Deactivate Identity API.
type V3DeactivateIdentityResponse struct {
	// If true, the deactivate operation was successful.
	Success bool `json:"success"`
}

func (v *V3DeactivateIdentityResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}
