// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DiscoverResponse struct {
	// A list of discovered attributes for the given ProveID.
	Results []Result `json:"results,omitempty"`
}

func (v *V3DiscoverResponse) GetResults() []Result {
	if v == nil {
		return nil
	}
	return v.Results
}

// #region class-body-v3discoverresponse
// #endregion class-body-v3discoverresponse
