// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainLinkResponse struct {
	// Success
	Success bool `json:"success"`
}

func (v *V3DomainLinkResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}

// #region class-body-v3domainlinkresponse
// #endregion class-body-v3domainlinkresponse
