// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainConfirmLinkResponse struct {
	// Success
	Success bool `json:"success"`
}

func (o *V3DomainConfirmLinkResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
