// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainConfirmLinkRequest struct {
	Pcid *string `json:"pcid,omitempty"`
}

func (o *V3DomainConfirmLinkRequest) GetPcid() *string {
	if o == nil {
		return nil
	}
	return o.Pcid
}
