// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainLinkedResponse struct {
	LinkedFrom   []LinkedFrom   `json:"linkedFrom,omitempty"`
	LinkedTo     []LinkedTo     `json:"linkedTo,omitempty"`
	RequestsFrom []RequestsFrom `json:"requestsFrom,omitempty"`
	RequestsTo   []RequestsTo   `json:"requestsTo,omitempty"`
}

func (v *V3DomainLinkedResponse) GetLinkedFrom() []LinkedFrom {
	if v == nil {
		return nil
	}
	return v.LinkedFrom
}

func (v *V3DomainLinkedResponse) GetLinkedTo() []LinkedTo {
	if v == nil {
		return nil
	}
	return v.LinkedTo
}

func (v *V3DomainLinkedResponse) GetRequestsFrom() []RequestsFrom {
	if v == nil {
		return nil
	}
	return v.RequestsFrom
}

func (v *V3DomainLinkedResponse) GetRequestsTo() []RequestsTo {
	if v == nil {
		return nil
	}
	return v.RequestsTo
}
