// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainUnlinkRequest struct {
	PcidFrom *string `json:"pcidFrom,omitempty"`
	PcidTo   *string `json:"pcidTo,omitempty"`
}

func (v *V3DomainUnlinkRequest) GetPcidFrom() *string {
	if v == nil {
		return nil
	}
	return v.PcidFrom
}

func (v *V3DomainUnlinkRequest) GetPcidTo() *string {
	if v == nil {
		return nil
	}
	return v.PcidTo
}
