// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainLinkRequest struct {
	Pcid   string   `json:"pcid"`
	Scopes []string `json:"scopes,omitempty"`
}

func (v *V3DomainLinkRequest) GetPcid() string {
	if v == nil {
		return ""
	}
	return v.Pcid
}

func (v *V3DomainLinkRequest) GetScopes() []string {
	if v == nil {
		return nil
	}
	return v.Scopes
}
