// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainUnlinkResponse struct {
	// Success
	Success bool `json:"success"`
}

func (v *V3DomainUnlinkResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}

// #region class-body-v3domainunlinkresponse
// #endregion class-body-v3domainunlinkresponse
