// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainIDResponse struct {
	// Customer friendly name
	Name string `json:"name"`
	// Customer ID
	Pcid string `json:"pcid"`
}

func (o *V3DomainIDResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *V3DomainIDResponse) GetPcid() string {
	if o == nil {
		return ""
	}
	return o.Pcid
}
