// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainConfirmLinkRequest struct {
	Pcid string `json:"pcid"`
}

func (v *V3DomainConfirmLinkRequest) GetPcid() string {
	if v == nil {
		return ""
	}
	return v.Pcid
}
