// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3DomainIDResponse struct {
	// Customer friendly name
	Name string `json:"name"`
	// Customer ID
	Pcid string `json:"pcid"`
}

func (v *V3DomainIDResponse) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *V3DomainIDResponse) GetPcid() string {
	if v == nil {
		return ""
	}
	return v.Pcid
}
