// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3EnrollIdentityResponse - Response body for the V3 Enroll Identity method.
type V3EnrollIdentityResponse struct {
	// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
	ProveID string `json:"proveId"`
	// If true, the request was successful and the identity was created.
	Success bool `json:"success"`
}

func (v *V3EnrollIdentityResponse) GetProveID() string {
	if v == nil {
		return ""
	}
	return v.ProveID
}

func (v *V3EnrollIdentityResponse) GetSuccess() bool {
	if v == nil {
		return false
	}
	return v.Success
}

// #region class-body-v3enrollidentityresponse
// #endregion class-body-v3enrollidentityresponse
