// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3EnrollIdentityResponse - Response body for the V3 Enroll Identity method.
type V3EnrollIdentityResponse struct {
	// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
	IdentityID string `json:"identityId"`
	// If true, the request was successful and the identity was created.
	Success bool `json:"success"`
}

func (o *V3EnrollIdentityResponse) GetIdentityID() string {
	if o == nil {
		return ""
	}
	return o.IdentityID
}

func (o *V3EnrollIdentityResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
