// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3FetchResponse - Response body for the Fetch API GET method.
type V3FetchResponse struct {
	// Array of identity attribute results containing attributeId, issuerId, and attributeValue.
	Results []FetchResult `json:"results"`
}

func (v *V3FetchResponse) GetResults() []FetchResult {
	if v == nil {
		return []FetchResult{}
	}
	return v.Results
}

// #region class-body-v3fetchresponse
// #endregion class-body-v3fetchresponse
