// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3GetIdentityResponse - Response body for the Identity API GET method.
type V3GetIdentityResponse struct {
	// If true, the identity is currently active.
	Active *bool `json:"active,omitempty"`
	// The carrier associated with this identity/mobile number.
	Carrier *string `json:"carrier,omitempty"`
	// A client-generated unique ID for a specific customer. This can be used by clients to link calls related to the same customer, across different requests or sessions.  The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// The country code associated with the customer/identity. This will be in the ISO 3166-1 A-2 format.
	CountryCode *string `json:"countryCode,omitempty"`
	// The time that this identity was created, in seconds since the Unix epoch.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// The time that this identity was created, in ISO 8601 format.
	CreationString *string `json:"creationString,omitempty"`
	// A string that is the unique identifier for the Prove Key on the device. Only applicable if you are leveraging Prove Unify.
	DeviceID *string `json:"deviceId,omitempty"`
	// A unique Prove-generated identifier for the enrolled identity. This is a UUID that can be used to reference the identity in future requests.
	IdentityID *string `json:"identityId,omitempty"`
	// The type of line associated with this identity/mobile number.
	LineType *string `json:"lineType,omitempty"`
	// The number of the mobile phone. Refer to the Prove Pre-Fill with Mobile Auth and Prove Identity with Mobile Auth documentation for situations where this field is not required. US phone numbers can be passed in with or without a leading +1. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber string `json:"phoneNumber"`
}

func (v *V3GetIdentityResponse) GetActive() *bool {
	if v == nil {
		return nil
	}
	return v.Active
}

func (v *V3GetIdentityResponse) GetCarrier() *string {
	if v == nil {
		return nil
	}
	return v.Carrier
}

func (v *V3GetIdentityResponse) GetClientCustomerID() *string {
	if v == nil {
		return nil
	}
	return v.ClientCustomerID
}

func (v *V3GetIdentityResponse) GetCountryCode() *string {
	if v == nil {
		return nil
	}
	return v.CountryCode
}

func (v *V3GetIdentityResponse) GetCreatedAt() *int64 {
	if v == nil {
		return nil
	}
	return v.CreatedAt
}

func (v *V3GetIdentityResponse) GetCreationString() *string {
	if v == nil {
		return nil
	}
	return v.CreationString
}

func (v *V3GetIdentityResponse) GetDeviceID() *string {
	if v == nil {
		return nil
	}
	return v.DeviceID
}

func (v *V3GetIdentityResponse) GetIdentityID() *string {
	if v == nil {
		return nil
	}
	return v.IdentityID
}

func (v *V3GetIdentityResponse) GetLineType() *string {
	if v == nil {
		return nil
	}
	return v.LineType
}

func (v *V3GetIdentityResponse) GetPhoneNumber() string {
	if v == nil {
		return ""
	}
	return v.PhoneNumber
}
