// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3GetIdentitiesByPhoneNumberResponse - Response body for the V3 Get Identities By Phone Number API.
type V3GetIdentitiesByPhoneNumberResponse struct {
	Items []LookupIdentityItem `json:"items,omitempty"`
}

func (v *V3GetIdentitiesByPhoneNumberResponse) GetItems() []LookupIdentityItem {
	if v == nil {
		return nil
	}
	return v.Items
}
