// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3IdentityDeactivateRequest - Request body for the V3 Deactivate Identity API.
type V3IdentityDeactivateRequest struct {
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
}

func (v *V3IdentityDeactivateRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}
