// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3MFAResponse - Response body for the V3 MFA API
type V3MFAResponse struct {
	// AuthToken is a one-time use JWT for client side possession SDK
	// authentication/authorization.
	AuthToken *string `json:"authToken,omitempty"`
	// Correlation ID is the unique ID that Prove generates for the flow.
	CorrelationID string `json:"correlationId"`
	Success       string `json:"success"`
}

func (o *V3MFAResponse) GetAuthToken() *string {
	if o == nil {
		return nil
	}
	return o.AuthToken
}

func (o *V3MFAResponse) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3MFAResponse) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}
