// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3MFABindResponse - Response body for the V3 MFA Bind API
type V3MFABindResponse struct {
	// Phone number that may have been discovered via Mobile Auth during the process.
	PhoneNumber string `json:"phoneNumber"`
	Success     string `json:"success"`
}

func (o *V3MFABindResponse) GetPhoneNumber() string {
	if o == nil {
		return ""
	}
	return o.PhoneNumber
}

func (o *V3MFABindResponse) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}
