// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3StartResponse struct {
	// A bearer token used by the client-side SDK.
	AuthToken string `json:"authToken"`
	// The unique ID that Prove generates for the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow - it cannot be reused outside of a single flow.
	CorrelationID string `json:"correlationId"`
	// The next set of allowed API calls in the same flow.
	Next map[string]string `json:"next"`
}

func (o *V3StartResponse) GetAuthToken() string {
	if o == nil {
		return ""
	}
	return o.AuthToken
}

func (o *V3StartResponse) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3StartResponse) GetNext() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Next
}
