// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3StartRequest struct {
	// If true, the customer can re-enter the OTP up to three times. Code must also be implemented. See client-side SDK guide for more details.
	AllowOTPRetry *bool `json:"allowOTPRetry,omitempty"`
	// The date of birth in one of these formats: YYYY-MM-DD, YYYY-MM, or MM-DD. Acceptable characters are: numeric with symbol '-'.
	//
	// It is recommended you do NOT pass this value into the Start step. Prove will attempt to pre-fill data using phone number only.
	Dob *string `json:"dob,omitempty"`
	// The email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// The URL where the end user will be redirected at the end of the Instant Link flow. Required only when `flowType=desktop`. Acceptable characters are: alphanumeric with symbols '-._+=/:?'. Max length is 128 characters.
	FinalTargetURL *string `json:"finalTargetUrl,omitempty"`
	// The type of device being user - either `desktop` for desktop web or `mobile` for iOS/Android native apps and mobile web.
	FlowType string `json:"flowType"`
	// The IP address of the mobile device. Acceptable characters are: numeric with symbols ':.'.
	IPAddress *string `json:"ipAddress,omitempty"`
	// The number of the mobile phone. Refer to the [Prove Pre-Fill Implementation guide](https://developer.prove.com/docs/prove-pre-fill-implementation-guide#implement-prove-pre-fill) and [Prove Identity Implementation guide](https://developer.prove.com/docs/prove-identity-implementation-guide#implement-prove-identity) for situations where this field is not required. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// The message body sent in the Instant Link (`flowType=desktop`) or OTP (`flowType=mobile`) SMS message. If not provided, the following default messages will be used:
	//
	// Instant Link: "Complete your verification. If you did not make this request, do not click the link. ####" _The verification URL replaces ####._
	//
	// OTP: "#### is your temporary code to continue your application. Caution: for your security, don't share this code with anyone." _Use ####, #####, or ###### to generate 4-6 digit verification codes respectively._
	//
	// Max length is 160 characters. Non-ASCII characters are allowed.
	SmsMessage *string `json:"smsMessage,omitempty"`
	// The full or last 4 digits of the social security number. Acceptable characters are: numeric.
	//
	// It is recommended you do NOT pass this value into the Start step. Prove will attempt to pre-fill data using phone number only.
	Ssn *string `json:"ssn,omitempty"`
}

func (v *V3StartRequest) GetAllowOTPRetry() *bool {
	if v == nil {
		return nil
	}
	return v.AllowOTPRetry
}

func (v *V3StartRequest) GetDob() *string {
	if v == nil {
		return nil
	}
	return v.Dob
}

func (v *V3StartRequest) GetEmailAddress() *string {
	if v == nil {
		return nil
	}
	return v.EmailAddress
}

func (v *V3StartRequest) GetFinalTargetURL() *string {
	if v == nil {
		return nil
	}
	return v.FinalTargetURL
}

func (v *V3StartRequest) GetFlowType() string {
	if v == nil {
		return ""
	}
	return v.FlowType
}

func (v *V3StartRequest) GetIPAddress() *string {
	if v == nil {
		return nil
	}
	return v.IPAddress
}

func (v *V3StartRequest) GetPhoneNumber() *string {
	if v == nil {
		return nil
	}
	return v.PhoneNumber
}

func (v *V3StartRequest) GetSmsMessage() *string {
	if v == nil {
		return nil
	}
	return v.SmsMessage
}

func (v *V3StartRequest) GetSsn() *string {
	if v == nil {
		return nil
	}
	return v.Ssn
}
