// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UnifyStatusRequest struct {
	// A client-generated unique ID for a specific request.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// The unique ID that Prove generates for the flow. It is returned
	// from the v3/unify endpoint and cannot be reused outside of a single flow.
	CorrelationID *string `json:"correlationId,omitempty"`
	// The number of the mobile phone. Required when `possessionType=none` in the initial Unify request.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

func (o *V3UnifyStatusRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

func (o *V3UnifyStatusRequest) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}

func (o *V3UnifyStatusRequest) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}
