// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3UnifyRequest - Request body for the V3 Unify API
type V3UnifyRequest struct {
	// Client Customer ID is a client-generated unique ID for a specific customer.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// Client Request ID is a client-generated unique ID for a specific session.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// Final target URL is only required when possessionType=desktop. The final target
	// URL is where the end user will be redirected at the end of Instant Link flow.
	// Acceptable characters are: alphanumeric with symbols '-._+=/:?'.
	FinalTargetURL *string `json:"finalTargetUrl,omitempty"`
	// Phone number is the number of the mobile phone. Optional in US, required in EU.
	// Not allowed when possessionType is 'none'. Acceptable characters are:
	// alphanumeric with symbols '+'.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// Possession type is based on the method used - either 'desktop' if using desktop,
	// 'mobile' for iOS/Android native apps and mobile web, or 'none' if no possession
	// check is required. Acceptable options are: 'desktop', 'mobile', and 'none'.
	PossessionType string `json:"possessionType"`
	// SMSMessage is an optional field to customize the message body sent in the
	// Instant Link (possessionType=desktop) or OTP (on mobile) SMS message.
	SmsMessage *string `json:"smsMessage,omitempty"`
}

func (o *V3UnifyRequest) GetClientCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.ClientCustomerID
}

func (o *V3UnifyRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

func (o *V3UnifyRequest) GetFinalTargetURL() *string {
	if o == nil {
		return nil
	}
	return o.FinalTargetURL
}

func (o *V3UnifyRequest) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *V3UnifyRequest) GetPossessionType() string {
	if o == nil {
		return ""
	}
	return o.PossessionType
}

func (o *V3UnifyRequest) GetSmsMessage() *string {
	if o == nil {
		return nil
	}
	return o.SmsMessage
}
