// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UnifyRequest struct {
	// If true, the customer can re-enter the OTP up to three times. Code must also be implemented. See client-side SDK guide for more details.
	AllowOTPRetry *bool `json:"allowOTPRetry,omitempty"`
	// If true, TrustScore verification will be performed.
	CheckReputation *bool `json:"checkReputation,omitempty"`
	// A client-generated unique ID for a specific customer.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// A client-generated unique ID to identify a specific customer across business lines.
	ClientHumanID *string `json:"clientHumanId,omitempty"`
	// A client-generated unique ID for a specific session. This can be used to identify specific requests.
	// The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted.
	// Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID string `json:"clientRequestId"`
	// The unique identifier for the Prove Key on the device.
	DeviceID *string `json:"deviceId,omitempty"`
	// The email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// The URL where the end user will be redirected at the end of Instant Link flow. Required when `possessionType=desktop`.
	// Acceptable characters are: alphanumeric with symbols '-._+=/:?'. Max length is 128 characters.
	FinalTargetURL *string `json:"finalTargetUrl,omitempty"`
	// The IP address of the customer. Acceptable characters are: Alphanumeric with '.:' symbols.
	IPAddress *string `json:"ipAddress,omitempty"`
	// The mobile phone number. US phone numbers can be passed in with or without a leading `+1`. International phone numbers require a leading `+1`. Use the appropriate endpoint URL based on the region the number originates from. Acceptable characters are: alphanumeric with symbols '+'.
	//
	// Required except when MobileAuth is used in US or a valid ProveID is provided.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// The type of device being used - either `desktop` if using a desktop,
	// `mobile` for iOS/Android native apps and mobile web, or `none` if no possession
	// check is required.
	PossessionType string `json:"possessionType"`
	// A unique ID to identify a specific customer obtained from a previous successful authentication.
	//
	// Required if phoneNumber is not present and mobileAuth is not enabled in the US or phoneNumber is not present in the EU.
	ProveID *string `json:"proveId,omitempty"`
	// If `true`, rebinds the Prove Key with the newly verified phone number.
	Rebind *bool `json:"rebind,omitempty"`
	// The message body sent in the Instant Link (`flowType=desktop`) or OTP (`flowType=mobile`) SMS message. If not provided, the following default messages will be used:
	// Instant Link: "Complete your verification. If you did not make this request, do not click the link. ####" The verification URL replaces ####.
	// OTP: "#### is your temporary code to continue your application. Caution: for your security, don't share this code with anyone." Use ####, #####, or ###### to generate 4-6 digit verification codes respectively.
	// Default language is English. Max length is 160 characters. Non-ASCII characters are allowed.
	SmsMessage *string `json:"smsMessage,omitempty"`
}

func (v *V3UnifyRequest) GetAllowOTPRetry() *bool {
	if v == nil {
		return nil
	}
	return v.AllowOTPRetry
}

func (v *V3UnifyRequest) GetCheckReputation() *bool {
	if v == nil {
		return nil
	}
	return v.CheckReputation
}

func (v *V3UnifyRequest) GetClientCustomerID() *string {
	if v == nil {
		return nil
	}
	return v.ClientCustomerID
}

func (v *V3UnifyRequest) GetClientHumanID() *string {
	if v == nil {
		return nil
	}
	return v.ClientHumanID
}

func (v *V3UnifyRequest) GetClientRequestID() string {
	if v == nil {
		return ""
	}
	return v.ClientRequestID
}

func (v *V3UnifyRequest) GetDeviceID() *string {
	if v == nil {
		return nil
	}
	return v.DeviceID
}

func (v *V3UnifyRequest) GetEmailAddress() *string {
	if v == nil {
		return nil
	}
	return v.EmailAddress
}

func (v *V3UnifyRequest) GetFinalTargetURL() *string {
	if v == nil {
		return nil
	}
	return v.FinalTargetURL
}

func (v *V3UnifyRequest) GetIPAddress() *string {
	if v == nil {
		return nil
	}
	return v.IPAddress
}

func (v *V3UnifyRequest) GetPhoneNumber() *string {
	if v == nil {
		return nil
	}
	return v.PhoneNumber
}

func (v *V3UnifyRequest) GetPossessionType() string {
	if v == nil {
		return ""
	}
	return v.PossessionType
}

func (v *V3UnifyRequest) GetProveID() *string {
	if v == nil {
		return nil
	}
	return v.ProveID
}

func (v *V3UnifyRequest) GetRebind() *bool {
	if v == nil {
		return nil
	}
	return v.Rebind
}

func (v *V3UnifyRequest) GetSmsMessage() *string {
	if v == nil {
		return nil
	}
	return v.SmsMessage
}
