// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UnifyBindResponse struct {
	// The number of the mobile phone used during the process.
	PhoneNumber string `json:"phoneNumber"`
	Success     string `json:"success"`
}

func (o *V3UnifyBindResponse) GetPhoneNumber() string {
	if o == nil {
		return ""
	}
	return o.PhoneNumber
}

func (o *V3UnifyBindResponse) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}
