// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3UnifyResponse struct {
	// The one-time use JWT for the client-side SDK.
	AuthToken *string `json:"authToken,omitempty"`
	// The unique ID that Prove generates for the flow. To continue the flow, the field will also be used for each of the subsequent API calls in the same flow - it cannot be reused outside of a single flow.
	CorrelationID string `json:"correlationId"`
	// The status of the Unify request.
	Success string `json:"success"`
}

func (o *V3UnifyResponse) GetAuthToken() *string {
	if o == nil {
		return nil
	}
	return o.AuthToken
}

func (o *V3UnifyResponse) GetCorrelationID() string {
	if o == nil {
		return ""
	}
	return o.CorrelationID
}

func (o *V3UnifyResponse) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}
