// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3ValidateResponseEvaluation struct {
}

type V3ValidateResponse struct {
	// True if a DOB or SSN needs to be passed in on the next step.
	ChallengeMissing bool `json:"challengeMissing"`
	// The evaluation result for the policy
	Evaluation map[string]V3ValidateResponseEvaluation `json:"evaluation,omitempty"`
	// The next set of allowed calls in the same flow.
	Next map[string]string `json:"next"`
	// The number of the mobile phone for which validation was performed.
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	// True if the phone number was validated.
	Success bool `json:"success"`
}

func (o *V3ValidateResponse) GetChallengeMissing() bool {
	if o == nil {
		return false
	}
	return o.ChallengeMissing
}

func (o *V3ValidateResponse) GetEvaluation() map[string]V3ValidateResponseEvaluation {
	if o == nil {
		return nil
	}
	return o.Evaluation
}

func (o *V3ValidateResponse) GetNext() map[string]string {
	if o == nil {
		return map[string]string{}
	}
	return o.Next
}

func (o *V3ValidateResponse) GetPhoneNumber() *string {
	if o == nil {
		return nil
	}
	return o.PhoneNumber
}

func (o *V3ValidateResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
