// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3VerifyStatusRequest - Request body for the V3 Verify Status API
type V3VerifyStatusRequest struct {
	// Client Request ID is a client-generated unique ID for a specific request. This can be used by clients to identify specific requests made to Prove Link. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Prove does not offer any functionality around the Client Request ID at this time, and this is expected to be added in a future release. NOTE: Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// Correlation ID is the unique ID that Prove generates for the flow. It is returned from the Start endpoint and cannot be reused outside of a single flow.
	CorrelationID *string `json:"correlationId,omitempty"`
}

func (o *V3VerifyStatusRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

func (o *V3VerifyStatusRequest) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}
