// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// V3VerifyStatusResponse - Response body for the V3 Verify Status API
type V3VerifyStatusResponse struct {
	PossessionResult string `json:"possessionResult"`
	Success          string `json:"success"`
	VerifyResult     string `json:"verifyResult"`
}

func (o *V3VerifyStatusResponse) GetPossessionResult() string {
	if o == nil {
		return ""
	}
	return o.PossessionResult
}

func (o *V3VerifyStatusResponse) GetSuccess() string {
	if o == nil {
		return ""
	}
	return o.Success
}

func (o *V3VerifyStatusResponse) GetVerifyResult() string {
	if o == nil {
		return ""
	}
	return o.VerifyResult
}
