// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// VerificationType - The verification method based on the use case and authorization level. Current allowed values: "verifiedUser", "accountOpening", "humanAssurance", "prefill", "prefillForBiz", "identityResolution", "validate".
type VerificationType string

const (
	VerificationTypeHumanAssurance     VerificationType = "humanAssurance"
	VerificationTypeVerifiedUser       VerificationType = "verifiedUser"
	VerificationTypeAccountOpening     VerificationType = "accountOpening"
	VerificationTypePrefill            VerificationType = "prefill"
	VerificationTypePrefillForBiz      VerificationType = "prefillForBiz"
	VerificationTypeIdentityResolution VerificationType = "identityResolution"
	VerificationTypeValidate           VerificationType = "validate"
)

func (e VerificationType) ToPointer() *VerificationType {
	return &e
}
func (e *VerificationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "humanAssurance":
		fallthrough
	case "verifiedUser":
		fallthrough
	case "accountOpening":
		fallthrough
	case "prefill":
		fallthrough
	case "prefillForBiz":
		fallthrough
	case "identityResolution":
		fallthrough
	case "validate":
		*e = VerificationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for VerificationType: %v", v)
	}
}

type V3VerifyRequest struct {
	// An optional list of addresses submitted by the user for validation. Used with verificationType=validate
	// to validate user-edited addresses against data-service records via SmartyStreets normalisation.
	Addresses []Address `json:"addresses,omitempty"`
	// A client-generated unique ID for a specific customer. This can be used by clients to link calls related to the same customer, across different requests or sessions. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Prove does not offer any functionality around the Client Customer ID. Do not include personally identifiable information (PII) in this field.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// An optional client-generated unique ID our Enterprise customer inputs for that consumer across business lines. If the Enterprise customer has been able to identify a consumer across business lines and has a unique identifier for the consumer, they would input this value to Prove. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include personally identifiable information (PII) in this field.
	ClientHumanID *string `json:"clientHumanId,omitempty"`
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// Indicates whether the consumer has provided consent. Accepts true or false. Defaults to false if not provided.
	Consent *bool `json:"consent,omitempty"`
	// The email address of the customer. Acceptable characters are: alphanumeric with symbols '@.+'.
	EmailAddress *string `json:"emailAddress,omitempty"`
	// The first name of the individual.
	FirstName *string `json:"firstName,omitempty"`
	// An optional list of identity attributes
	IdentityAttributes []IdentityAttribute `json:"identityAttributes,omitempty"`
	// The public IP address of the session of the individual. Acceptable characters
	IPAddress *string `json:"ipAddress,omitempty"`
	// The last name of the individual.
	LastName *string `json:"lastName,omitempty"`
	// The mobile phone number. US and Canada phone numbers can be passed in with or without a leading `+1`.
	// International phone numbers require a leading `+` followed by the country code. Use the appropriate endpoint URL
	// based on the region the number originates from. Acceptable characters are: alphanumeric with symbols '+'.
	PhoneNumber string `json:"phoneNumber"`
	// PreviousCorrelationID is the correlationId returned by the preceding prefill response.
	// When provided, it is echoed back in the validate response to link the two flows.
	PreviousCorrelationID *string `json:"previousCorrelationId,omitempty"`
	// The User agent of the session of the individual.
	UserAgent *string `json:"userAgent,omitempty"`
	// The verification method based on the use case and authorization level. Current allowed values: "verifiedUser", "accountOpening", "humanAssurance", "prefill", "prefillForBiz", "identityResolution", "validate".
	VerificationType VerificationType `json:"verificationType"`
}

func (v *V3VerifyRequest) GetAddresses() []Address {
	if v == nil {
		return nil
	}
	return v.Addresses
}

func (v *V3VerifyRequest) GetClientCustomerID() *string {
	if v == nil {
		return nil
	}
	return v.ClientCustomerID
}

func (v *V3VerifyRequest) GetClientHumanID() *string {
	if v == nil {
		return nil
	}
	return v.ClientHumanID
}

func (v *V3VerifyRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

func (v *V3VerifyRequest) GetConsent() *bool {
	if v == nil {
		return nil
	}
	return v.Consent
}

func (v *V3VerifyRequest) GetEmailAddress() *string {
	if v == nil {
		return nil
	}
	return v.EmailAddress
}

func (v *V3VerifyRequest) GetFirstName() *string {
	if v == nil {
		return nil
	}
	return v.FirstName
}

func (v *V3VerifyRequest) GetIdentityAttributes() []IdentityAttribute {
	if v == nil {
		return nil
	}
	return v.IdentityAttributes
}

func (v *V3VerifyRequest) GetIPAddress() *string {
	if v == nil {
		return nil
	}
	return v.IPAddress
}

func (v *V3VerifyRequest) GetLastName() *string {
	if v == nil {
		return nil
	}
	return v.LastName
}

func (v *V3VerifyRequest) GetPhoneNumber() string {
	if v == nil {
		return ""
	}
	return v.PhoneNumber
}

func (v *V3VerifyRequest) GetPreviousCorrelationID() *string {
	if v == nil {
		return nil
	}
	return v.PreviousCorrelationID
}

func (v *V3VerifyRequest) GetUserAgent() *string {
	if v == nil {
		return nil
	}
	return v.UserAgent
}

func (v *V3VerifyRequest) GetVerificationType() VerificationType {
	if v == nil {
		return VerificationType("")
	}
	return v.VerificationType
}

// #region class-body-v3verifyrequest
// #endregion class-body-v3verifyrequest
