// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3VerifyBatchRequest struct {
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// Batch of verify requests to process. The array length cannot exceed 1000 items.
	Items []VerifyItem `json:"items"`
}

func (v *V3VerifyBatchRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

func (v *V3VerifyBatchRequest) GetItems() []VerifyItem {
	if v == nil {
		return []VerifyItem{}
	}
	return v.Items
}
