// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3VerifyStatusRequest struct {
	// A client-generated unique ID for a specific request. This can be used by clients to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Prove does not offer any functionality around the Client Request ID. Do not include personally identifiable information (PII) in this field.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// The unique ID that Prove generates for the flow. It is returned from the v3/verify endpoint and cannot be reused outside of a single flow.
	CorrelationID *string `json:"correlationId,omitempty"`
}

func (o *V3VerifyStatusRequest) GetClientRequestID() *string {
	if o == nil {
		return nil
	}
	return o.ClientRequestID
}

func (o *V3VerifyStatusRequest) GetCorrelationID() *string {
	if o == nil {
		return nil
	}
	return o.CorrelationID
}
