// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3VerifyBatchResponse struct {
	// The input ClientRequestID.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// The unique ID that Prove generates for the flow.
	CorrelationID string                  `json:"correlationId"`
	Results       []VerifyBatchResultItem `json:"results,omitempty"`
}

func (v *V3VerifyBatchResponse) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

func (v *V3VerifyBatchResponse) GetCorrelationID() string {
	if v == nil {
		return ""
	}
	return v.CorrelationID
}

func (v *V3VerifyBatchResponse) GetResults() []VerifyBatchResultItem {
	if v == nil {
		return nil
	}
	return v.Results
}
