// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3VerifyBatchRequest struct {
	// A client-generated unique ID for a specific session. This can be used to identify specific requests. The format of this ID is defined by the client - Prove recommends using a GUID, but any format can be accepted. Do not include Personally Identifiable Information (PII) in this field.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// Batch of verify requests to process. The array length cannot exceed 1000 items.
	Items []VerifyBatchRequestItem `json:"items"`
}

func (v *V3VerifyBatchRequest) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

func (v *V3VerifyBatchRequest) GetItems() []VerifyBatchRequestItem {
	if v == nil {
		return []VerifyBatchRequestItem{}
	}
	return v.Items
}
