// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3VerifyResponseEvaluation struct {
}

type V3VerifyResponse struct {
	// (required IF verificationType=VerifiedUser)
	AdditionalIdentities []Identity `json:"additionalIdentities,omitempty"`
	// The input ClientCustomerID.
	ClientCustomerID *string `json:"clientCustomerId,omitempty"`
	// The input ClientHumanID.
	ClientHumanID *string `json:"clientHumanId,omitempty"`
	// The input ClientRequestID.
	ClientRequestID *string `json:"clientRequestId,omitempty"`
	// The unique ID that Prove generates for the flow.
	CorrelationID string `json:"correlationId"`
	// The evaluation result for the policy. This is an upcoming field but is not yet enabled.
	Evaluation map[string]V3VerifyResponseEvaluation `json:"evaluation,omitempty"`
	Identity   *Identity                             `json:"identity,omitempty"`
	// The input phone number.
	PhoneNumber string `json:"phoneNumber"`
	// A Prove-generated identifier for the consumer.
	// (required IF verificationType=VerifiedUser)
	ProveID *string `json:"proveId,omitempty"`
	// A persistent ID that uniquely identifies a telephone subscriber.
	// (required IF verificationType=VerifiedUser)
	ProvePhoneAlias *string `json:"provePhoneAlias,omitempty"`
	// The result of verification.
	Success string `json:"success"`
}

func (v *V3VerifyResponse) GetAdditionalIdentities() []Identity {
	if v == nil {
		return nil
	}
	return v.AdditionalIdentities
}

func (v *V3VerifyResponse) GetClientCustomerID() *string {
	if v == nil {
		return nil
	}
	return v.ClientCustomerID
}

func (v *V3VerifyResponse) GetClientHumanID() *string {
	if v == nil {
		return nil
	}
	return v.ClientHumanID
}

func (v *V3VerifyResponse) GetClientRequestID() *string {
	if v == nil {
		return nil
	}
	return v.ClientRequestID
}

func (v *V3VerifyResponse) GetCorrelationID() string {
	if v == nil {
		return ""
	}
	return v.CorrelationID
}

func (v *V3VerifyResponse) GetEvaluation() map[string]V3VerifyResponseEvaluation {
	if v == nil {
		return nil
	}
	return v.Evaluation
}

func (v *V3VerifyResponse) GetIdentity() *Identity {
	if v == nil {
		return nil
	}
	return v.Identity
}

func (v *V3VerifyResponse) GetPhoneNumber() string {
	if v == nil {
		return ""
	}
	return v.PhoneNumber
}

func (v *V3VerifyResponse) GetProveID() *string {
	if v == nil {
		return nil
	}
	return v.ProveID
}

func (v *V3VerifyResponse) GetProvePhoneAlias() *string {
	if v == nil {
		return nil
	}
	return v.ProvePhoneAlias
}

func (v *V3VerifyResponse) GetSuccess() string {
	if v == nil {
		return ""
	}
	return v.Success
}
