// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VerifyBatchResultItemEvaluation struct {
}

type VerifyBatchResultItem struct {
	// (required IF verificationType=VerifiedUser)
	AdditionalIdentities []Identity `json:"additionalIdentities,omitempty"`
	// Prove’s tiered confidence metric, ranging from -1 to 3, that dynamically adapts to user behavior and various authentication keys. It allows for adaptive security policies, meaning you can require different levels of verification for different types of transactions.
	AssuranceLevel string `json:"assuranceLevel"`
	// TODO: usage comment. Chances are this will be a part of Identity struct.
	Businesses []Business `json:"businesses,omitempty"`
	// The input ClientCustomerID.
	ClientCustomerID string `json:"clientCustomerId"`
	// The input ClientHumanID.
	// (required IF verificationType=VerifiedUser)
	ClientHumanID *string `json:"clientHumanId,omitempty"`
	// An error message for this corresponding specific verification.
	Error *string `json:"error,omitempty"`
	// The evaluation result for the policy. This is an upcoming field but is not yet enabled.
	Evaluation     map[string]VerifyBatchResultItemEvaluation `json:"evaluation,omitempty"`
	Identity       *Identity                                  `json:"identity,omitempty"`
	LinkedAccounts []LinkedAccount                            `json:"linkedAccounts,omitempty"`
	// The input phone number.
	PhoneNumber    string  `json:"phoneNumber"`
	ProveAccountID *string `json:"proveAccountId,omitempty"`
	// A Prove-generated identifier for the consumer.
	// (required IF verificationType=VerifiedUser)
	ProveID *string `json:"proveId,omitempty"`
	// A persistent ID that uniquely identifies a telephone subscriber.
	// (required IF verificationType=VerifiedUser)
	ProvePhoneAlias *string `json:"provePhoneAlias,omitempty"`
	// The result of verification.
	Success string `json:"success"`
}

func (v *VerifyBatchResultItem) GetAdditionalIdentities() []Identity {
	if v == nil {
		return nil
	}
	return v.AdditionalIdentities
}

func (v *VerifyBatchResultItem) GetAssuranceLevel() string {
	if v == nil {
		return ""
	}
	return v.AssuranceLevel
}

func (v *VerifyBatchResultItem) GetBusinesses() []Business {
	if v == nil {
		return nil
	}
	return v.Businesses
}

func (v *VerifyBatchResultItem) GetClientCustomerID() string {
	if v == nil {
		return ""
	}
	return v.ClientCustomerID
}

func (v *VerifyBatchResultItem) GetClientHumanID() *string {
	if v == nil {
		return nil
	}
	return v.ClientHumanID
}

func (v *VerifyBatchResultItem) GetError() *string {
	if v == nil {
		return nil
	}
	return v.Error
}

func (v *VerifyBatchResultItem) GetEvaluation() map[string]VerifyBatchResultItemEvaluation {
	if v == nil {
		return nil
	}
	return v.Evaluation
}

func (v *VerifyBatchResultItem) GetIdentity() *Identity {
	if v == nil {
		return nil
	}
	return v.Identity
}

func (v *VerifyBatchResultItem) GetLinkedAccounts() []LinkedAccount {
	if v == nil {
		return nil
	}
	return v.LinkedAccounts
}

func (v *VerifyBatchResultItem) GetPhoneNumber() string {
	if v == nil {
		return ""
	}
	return v.PhoneNumber
}

func (v *VerifyBatchResultItem) GetProveAccountID() *string {
	if v == nil {
		return nil
	}
	return v.ProveAccountID
}

func (v *VerifyBatchResultItem) GetProveID() *string {
	if v == nil {
		return nil
	}
	return v.ProveID
}

func (v *VerifyBatchResultItem) GetProvePhoneAlias() *string {
	if v == nil {
		return nil
	}
	return v.ProvePhoneAlias
}

func (v *VerifyBatchResultItem) GetSuccess() string {
	if v == nil {
		return ""
	}
	return v.Success
}
