workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://raw.githubusercontent.com/payfone/prove-openapi/main/orchestration.yaml
        registry:
            location: registry.speakeasyapi.dev/prove/prove-dev/my-source
targets:
    my-first-target:
        target: go
        source: my-source
